#!/usr/bin/env python3
"""Bake 5TRSCRN — the teletext title page the track menu shows — into a C header.

    python3 tools/gen_titlescreen.py revs.ssd src/platform/titlescreen.h

⭐ WHY A BLOB AND NOT A PAINT ROUTINE.  On the real machine REVSMEN does `*LOAD 5TRSCRN`, which
drops 1 KB straight into MODE 7 screen RAM at $7C00 — there is no VDU stream to reproduce, and
nothing to interpret.  `tools/bbc_probe_trackmenu.mjs` confirms it end to end: the page a real BBC
DISPLAYS is byte-identical to the file on the disc.  So the faithful mechanism is a copy, and the
only honest form for the asset is the bytes.

⚠ The output is GIT-IGNORED, for the same reason as `src/gen/revs_tracks.c`: it is a kilobyte of
Superior/Acornsoft's own screen data, and this repository does not carry the disc's bytes.  It is
generated on demand — `make titlescreen`, and any `make gen` — from a local revs.ssd.
"""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ssd_map import read_catalogue  # noqa: E402

NAME = "5TRSCRN"
LOAD = 0x7C00
SIZE = 0x400


def main():
    ssd = sys.argv[1] if len(sys.argv) > 1 else "revs.ssd"
    out = sys.argv[2] if len(sys.argv) > 2 else "src/platform/titlescreen.h"

    img = open(ssd, "rb").read()
    cat = read_catalogue(img)
    hit = next((f for f in cat["files"] if f["name"].upper() == NAME), None)
    if hit is None:
        raise SystemExit(f"{ssd}: no file '{NAME}'")

    # ⚠ Check the load address rather than assume it: the whole point of the blob is that it is
    # copied to exactly where the MOS would have put it, and a file that loads elsewhere is a
    # different asset with the same name.
    if hit["load"] & 0xFFFF != LOAD or hit["length"] != SIZE:
        raise SystemExit(
            f"{NAME}: expected load ${LOAD:04X} length ${SIZE:X}, "
            f"got load ${hit['load'] & 0xFFFF:04X} length ${hit['length']:X}"
        )

    off = hit["start"] * 256
    data = img[off:off + SIZE]
    if len(data) != SIZE:
        raise SystemExit(f"{NAME}: short read ({len(data)} of {SIZE})")

    with open(out, "w") as f:
        f.write(f"""/* GENERATED by tools/gen_titlescreen.py from {NAME} on revs.ssd — DO NOT EDIT.
 *
 * The teletext title page REVSMEN `*LOAD`s at ${LOAD:04X} before it draws the circuit menu.  A
 * verbatim copy of the disc file: `tools/bbc_probe_trackmenu.mjs` recorded what a real BBC
 * displays here and it is byte-identical to these {SIZE} bytes, so the page needs no interpreting
 * — src/platform/trackmenu.c copies it into MODE 7 screen RAM exactly as `*LOAD` does.
 */
#ifndef REVS_TITLESCREEN_H
#define REVS_TITLESCREEN_H

#define REVS_TITLESCREEN_LO   0x{LOAD:04X}u
#define REVS_TITLESCREEN_LEN  0x{SIZE:04X}u

static const unsigned char revs_titlescreen[REVS_TITLESCREEN_LEN] = {{
""")
        for i in range(0, SIZE, 12):
            row = ", ".join(f"0x{b:02X}" for b in data[i:i + 12])
            f.write(f"    {row},\n")
        f.write("};\n\n#endif /* REVS_TITLESCREEN_H */\n")

    print(f"# wrote {out}: {SIZE} bytes of {NAME} (load ${LOAD:04X})")


if __name__ == "__main__":
    main()
