#!/usr/bin/env python3
"""Generate src/platform/mos_font.h — the RACE VIEW's 8x8 character generator.

    python3 tools/gen_mos_font.py [--rom=PATH]     # -> src/platform/mos_font.h

── WHAT THIS IS ──────────────────────────────────────────────────────────────────────────────

`vdu_char_def` ($5092) has two arms, selected by `$64` bit 7, and they use two DIFFERENT fonts
(docs/bbc-hardware.md §MOS calls).  The MODE 7 arm calls OSWRCH and the SAA5050 draws the cell —
that font is `src/platform/teletext_font.h`.  **This is the other arm.**  $5096 puts the
character code in the OSWORD control block at $62C3, asks `OSWORD 10` for an 8x8 bitmap, and
plots the eight returned bytes into the frame buffer itself.

That bitmap is the **MOS 1.20 ROM's software font**, and this table IS those bytes: the ROM keeps
codes $20-$7F as 96 x 8 bytes at its very start (&C000-&C2FF), one byte per row, bit 7 the
leftmost pixel — exactly what OSWORD 10 returns, so nothing transforms them on the way to the
screen.  The ROM is jsbeeb's `os.rom` (byte-identical to b2's `OS12.ROM`), the one every
`make refloop` capture was taken with; its SHA-1 is checked below so a different MOS cannot be
extracted silently.  (User decision, 2026-09-30: the real font, not a drawn one.)

── WHAT THE ENGINE ASKS FOR ──────────────────────────────────────────────────────────────────

Measured on a real BBC over a 200-frame Silverstone practice race
(`make refloop-charset`, i.e. bbc_refloop_race.mjs --charset):

    88 calls, 15 distinct codes, 76 distinct cells, $64 == $00 every time
    $20 $2e $31 $3a $42 $4c $4f $54 $61 $65 $69 $6d $70 $73 $74
    i.e. ' ' '.' '1' ':' 'B' 'L' 'O' 'T' 'a' 'e' 'i' 'm' 'p' 's' 't'
    printed from $3d57 (print_spaces), $4dc4 (text_script_interp), $37eb, $37fe,
    and $7ba9/$7bb8 — the dashboard overlay

⚠ That is ONE session's vocabulary — a practice lap readout, mixed case.  Competition adds
driver names, digits and qualifying text, so the set is a FLOOR, not the closed surface.  The
whole printable range $20-$7F is therefore extracted rather than just the fifteen measured codes,
and `mos.cpp` counts any request outside it instead of quietly returning a blank.

── ⭐ DOUBLE WIDTH, AND WHY IT DECIDES THE GLYPH GEOMETRY ────────────────────────────────────

`vdu_char_def` has a THIRD entry nobody had noticed, and it is the gear indicator:

    508c  STA $62C3        ; stash the character code...
    508f  JMP $509D        ; ...and jump PAST $509B's `LDA #0 / STA $77`

so a caller that pre-loads `$77` reaches the arm at $50AE that reading the code says is dead.
That arm is a DOUBLE-WIDTH renderer: with `$77` bit 7 clear, `AND #$F0` keeps the glyph's left
four columns; with it set, `ASL A` x4 lifts the right four into their place.  Each half becomes
the four (double-width) pixels of one MODE 5 cell, so one glyph is drawn across two cells.

Its only caller is the gearstick readout at $42D0 — measured, not deduced:

    42d0  LDA #$22 / STA $62CC / STA $77    ; column 34, and $77 = $22 -> LEFT half
    42d7  LDA #$D7 / STA $62CD              ; frame-buffer row 215
    42dc  LDX $40 / LDA $3779,X             ; the current gear -> 'N', '1', '2', ...
    42e1  JSR $508C                         ; plot the left half in column 34
    42e4  LDX #$FF / STX $77                ; $77 = $FF -> RIGHT half
    42e8  JSR $508C                         ; ...and the right half in column 35

Confirmed on a real BBC by `make refloop-charset`: 4 entries at $509D from $508F, `$77` in
{$22, $FF}, character codes {$4E, $31} — 'N' and '1', exactly the gears a practice run engages.

⭐ That is why the ROM's glyphs sit where they do: a narrow glyph like '1' has its stem on bits
4..3, straddling the nibble split, so each half of the gear indicator gets one column.  (A drawn
stand-in used here until 2026-09-30 had to reproduce that by hand, and got it wrong once: 18
pixels of the dial band against a real BBC in first gear.)

── THE LAYOUT ────────────────────────────────────────────────────────────────────────────────

    glyph = g_mosFont + ((code - 0x20) << 3)
"""

import argparse
import hashlib
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "src", "platform", "mos_font.h")
ROM = os.path.join(REPO, "tools", "jsbeeb", "public", "roms", "os.rom")
ROM_SHA1 = "0d9bcaf6a393c9ce2359ed700ddb53c232c2c45d"   # MOS 1.20

FIRST = 0x20
LAST = 0x7F


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=ROM)
    args = ap.parse_args()
    rom = open(args.rom, "rb").read()
    if len(rom) != 16384 or hashlib.sha1(rom).hexdigest() != ROM_SHA1:
        print(f"{args.rom}: not MOS 1.20 (want 16384 bytes, SHA-1 {ROM_SHA1})", file=sys.stderr)
        return 1
    count = LAST - FIRST + 1

    out = []
    out.append("/* mos_font.h — GENERATED by tools/gen_mos_font.py.  Do not edit by hand.")
    out.append(" *")
    out.append(" * The race view's 8x8 character generator: what `OSWORD 10` hands back to")
    out.append(" * vdu_char_def's bitmap arm ($5096), which plots the eight bytes straight into the")
    out.append(" * frame buffer.  EXTRACTED from the MOS 1.20 ROM (&C000-&C2FF): one byte per row,")
    out.append(" * bit 7 = leftmost pixel, exactly as the ROM holds it.")
    out.append(" */")
    out.append("#ifndef REVS_MOS_FONT_H")
    out.append("#define REVS_MOS_FONT_H")
    out.append("")
    out.append("/* ⚠ NO #include <stdint.h> here, deliberately: the Amiga build's SASCCompat.h has")
    out.append(" * already typedef'd int8_t and the framework's compat stdint.h then conflicts with")
    out.append(" * it.  teletext_font.h holds the same line — a generated table includes nothing and")
    out.append(" * takes its types from whoever includes it. */")
    out.append("")
    out.append(f"#define MOS_FONT_FIRST 0x{FIRST:02X}   /* space */")
    out.append(f"#define MOS_FONT_LAST  0x{LAST:02X}   /* DELETE */")
    out.append(f"#define MOS_FONT_COUNT {count}")
    out.append("#define MOS_FONT_HEIGHT 8")
    out.append("")
    out.append("/* glyph = g_mosFont + ((code - MOS_FONT_FIRST) << 3) */")
    out.append("static const uint8_t g_mosFont[MOS_FONT_COUNT][MOS_FONT_HEIGHT] = {")
    for code in range(FIRST, LAST + 1):
        o = (code - FIRST) * 8
        body = ", ".join(f"0x{b:02X}" for b in rom[o:o + 8])
        ch = chr(code) if 0x21 <= code <= 0x7E and code != 0x5C else " "
        out.append(f"    {{ {body} }},   /* ${code:02X} {ch} */")
    out.append("};")
    out.append("")
    out.append("#endif /* REVS_MOS_FONT_H */")

    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"{OUT}: {count} glyphs, {count * 8} bytes from {args.rom}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
