/* Native-twin validation harness.
 *
 * For each function listed in transpile.py's VALIDATE_FUNCS, two versions exist:
 *   <name>()         — the native reimplementation        (src/gen/revs_native.c)
 *   <name>__t6502()  — the faithful 6502 transliteration  (src/gen/revs_gen.c)
 *
 * This harness runs both on the SAME randomised pre-state and diffs the full machine
 * state (all 64 KB of mem[] plus the CPU registers/flags).
 *
 * Build:  make validate            Run one:  make validate FN=<substring>
 *
 * ============================================================================
 * ⭐ WHY THIS FILE LOOKS OVER-ENGINEERED FOR ZERO TWINS
 * ============================================================================
 * The nastiest bug class on the Atari port was **passes `make validate` green, breaks
 * at runtime**, and it bit three separate times.  The postmortem's §3.1 conclusion was
 * to make each failure mode STRUCTURALLY IMPOSSIBLE from twin #1 rather than patching
 * the harness after each one.  So, before the first twin exists:
 *
 *  1. FIXTURE-OR-FAIL.  A function registered in VALIDATE_FUNCS but with no fixture
 *     here used to print PASS having run ZERO comparisons — a vacuous green.  The
 *     transpiler now emits every validated name into src/gen/revs_validate_list.h, and
 *     main() FAILS if any listed name has no registered fixture.  See check_coverage().
 *
 *  2. NO "INCIDENTAL" REGISTER BUCKET.  The old harness reported exit-register diffs as
 *     "incidental" and moved on — but a twin's exit register consumed by a transpiled
 *     caller is a real contract, and one such diff (an exit A=0) shipped a live bug.
 *     Here every fixture must DECLARE which registers are live on exit
 *     (LIVE_NONE / LIVE_A / …).  Anything declared live is a hard failure; anything not
 *     declared is asserted DEAD, which forces the author to have checked the call sites.
 *
 *  3. ENDIANNESS CANNOT HIDE.  mem[] is little-endian (6502).  The Amiga 68000 is
 *     big-endian and this host is little-endian, so aliasing mem[] as uint16_t* / uint32_t*
 *     reads correct here and byte-swapped on the target — green host run, garbage on the
 *     Amiga.  Two countermeasures: `make endian-lint` greps for such aliases, and
 *     ENDIAN_NOTE below records the rule at the point of temptation.  A twin that needs
 *     16/32-bit values lifts them into locals and touches mem[] byte-wise.
 *
 *  4. RANDOMISED INPUTS INCLUDING GATING BYTES.  Fixtures randomise the WHOLE 64 KB by
 *     default (fill_random), not a hand-authored subset, so no branch stays untested
 *     because its gating byte happened to be zero in every case.
 * ============================================================================
 *
 * Deterministic: fixed-seed xorshift PRNG (no wall-clock / rand()), so a green run is
 * reproducible and a regression is bisectable.
 */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "../src/cpu/cpu.h"

/* Generated by tools/transpile.py: VALIDATE_NAMES[] — every name in VALIDATE_FUNCS.
   Absent until the first `make gen`, so tolerate that while scaffolding. */
#if defined(__has_include)
#  if __has_include("../src/gen/revs_validate_list.h")
#    include "../src/gen/revs_validate_list.h"
#    define HAVE_VALIDATE_LIST 1
#  endif
#endif
#ifndef HAVE_VALIDATE_LIST
static const char* const VALIDATE_NAMES[] = { 0 };
static const char* const NATIVE_UNVALIDATED_NAMES[] = { 0 };
#endif

/* ENDIAN_NOTE: never alias mem[] as uint16_t* / uint32_t* for a general value.  The one
   safe case is a uniform-byte broadcast store (all lanes equal => endianness-neutral),
   and even then the address must be even and the region ISR-untouched.
   See docs/m68k-optimisation.md. */

static uint32_t rng = 0x9D6F1234u;
static uint32_t xs(void) { uint32_t x = rng; x ^= x << 13; x ^= x >> 17; x ^= x << 5; return rng = x; }

/* ---------------------------------------------------------------- test filter */
static char** g_filter  = 0;
static int    g_nfilter = 0;
static int want(const char* name) {
    if (g_nfilter == 0) return 1;
    for (int i = 0; i < g_nfilter; i++)
        if (strstr(name, g_filter[i])) return 1;
    return 0;
}

/* ------------------------------------------------- fixture coverage registry */
enum { MAX_FIXTURES = 256 };
static const char* g_registered[MAX_FIXTURES];
static int         g_nregistered = 0;
static void register_fixture(const char* name) {
    if (g_nregistered < MAX_FIXTURES) g_registered[g_nregistered++] = name;
}
static int is_registered(const char* name) {
    for (int i = 0; i < g_nregistered; i++)
        if (strcmp(g_registered[i], name) == 0) return 1;
    return 0;
}
/* FIXTURE-OR-FAIL: every validated function must have a fixture.  A missing one is a
   HARD FAILURE, not a warning — that is the whole point (see the header, §1). */
static int check_coverage(void) {
    int missing = 0;
    for (int i = 0; VALIDATE_NAMES[i]; i++) {
        if (!is_registered(VALIDATE_NAMES[i])) {
            printf("[NO FIXTURE] %s is in VALIDATE_FUNCS but has no test here — "
                   "a PASS for it would be vacuous (0 comparisons run)\n",
                   VALIDATE_NAMES[i]);
            missing++;
        }
    }
    return missing;
}

/* ⭐ THE OTHER HALF OF check_coverage: twins that have NO fixture BY DECLARATION.
   transpile.py's NATIVE_FUNCS is for a native reimplementation whose oracle cannot be run
   here at all — the one member is race_main_loop, whose first act on any pre-state is to
   execute a whole frame of the engine.  Silence would be the vacuous-green failure mode
   wearing a different hat, so the names are PRINTED on every run together with what does
   gate them.  Returns 0: this is a report, not a failure. */
static int report_unvalidated_natives(void)
{
    int i;
    for (i = 0; NATIVE_UNVALIDATED_NAMES[i]; i++)
        printf("%-32s NO FIXTURE BY DECLARATION (transpile.py NATIVE_FUNCS) — "
               "gated by `make determinism`, not by this harness\n",
               NATIVE_UNVALIDATED_NAMES[i]);
    return 0;
}

/* ------------------------------------------------- live-exit-register contract */
enum {
    LIVE_NONE = 0,
    LIVE_A = 1 << 0, LIVE_X = 1 << 1, LIVE_Y = 1 << 2, LIVE_S = 1 << 3,
    LIVE_FLAGS = 1 << 4          /* N/V/Z/C */
};

/* Per-test contract mask: addresses excluded from the mem[] diff.  Use ONLY for cells
   PROVEN dead after the function returns (no reader before the next write).  Scoped —
   set before a test, clear after — so it never relaxes another function's contract. */
static const uint16_t* g_ignore   = 0;
static int             g_ignore_n = 0;
static void set_ignore(const uint16_t* addrs, int n) { g_ignore = addrs; g_ignore_n = n; }

void platform_test_init_headless(void);
void platform_test_tick_clock(int on);
void platform_test_clock_addr(uint16_t a);

/* ⭐⭐ THE HARDWARE-WRITE TRACE (src/platform/platform_cbridge.cpp).  mem[] is only half of
   what a 6502 routine can produce; the other half is $FC00-$FEFF, and for a display or
   timer routine it is nearly ALL of the output.  Diffing it is not optional — see the
   sabotage note over test_irq1v_band_schedule(). */
enum { HWLOG_MAX = 8192 };
/* The SMC trap channel (src/platform/Platform.cpp) — see the comparison in diff_run. */
extern volatile unsigned long g_smcUnhandled;
extern volatile uint16_t      g_smcSite;
extern volatile uint16_t      g_smcValue;

extern uint16_t g_hwLogAddr[HWLOG_MAX];
extern uint8_t  g_hwLogVal[HWLOG_MAX];
extern unsigned g_hwLogN;
extern unsigned g_hwLogOverflow;

static void fill_random(uint8_t* buf) {
    uint32_t* w = (uint32_t*)buf;
    for (int i = 0; i < 65536 / 4; i++) w[i] = xs();
}

static Cpu6502 zero_cpu(void) {
    Cpu6502 c; memset(&c, 0, sizeof c); c.S = 0xFF; return c;
}

/* Run native vs __t6502 on the SAME pre-state; diff full mem[] + the declared-live
   registers, and assert the undeclared ones really are dead.
   Returns the number of failing cases. */
static int diff_run(const char* name, const uint8_t* pre, Cpu6502 pre_cpu,
                    void (*native)(void), void (*t6502)(void), unsigned liveMask,
                    int t, int* printed)
{
    static uint8_t  ref_mem[65536];
    static uint16_t ref_hw_addr[HWLOG_MAX];
    static uint8_t  ref_hw_val[HWLOG_MAX];

    unsigned long smc_before = g_smcUnhandled;

    memcpy((void*)mem, pre, 65536); cpu = pre_cpu;
    g_hwLogN = 0; g_hwLogOverflow = 0;
    t6502();
    memcpy(ref_mem, (void*)mem, sizeof ref_mem);
    Cpu6502 ref_cpu = cpu;
    unsigned ref_hw_n = g_hwLogN, ref_hw_ovf = g_hwLogOverflow;
    memcpy(ref_hw_addr, g_hwLogAddr, ref_hw_n * sizeof ref_hw_addr[0]);
    memcpy(ref_hw_val,  g_hwLogVal,  ref_hw_n * sizeof ref_hw_val[0]);
    unsigned long ref_smc_n = g_smcUnhandled - smc_before;
    uint16_t ref_smc_site = g_smcSite, ref_smc_value = g_smcValue;

    smc_before = g_smcUnhandled;
    memcpy((void*)mem, pre, 65536); cpu = pre_cpu;
    g_hwLogN = 0; g_hwLogOverflow = 0;
    native();

    for (int i = 0; i < g_ignore_n; i++) ref_mem[g_ignore[i]] = mem[g_ignore[i]];

    int failed = 0;
    if (memcmp((const void*)mem, ref_mem, 65536) != 0) {
        failed = 1;
        for (int i = 0; i < 65536 && *printed < 12; i++)
            if (mem[i] != ref_mem[i]) {
                printf("[MEM DIFF] %s case %d  $%04X  ref=$%02X native=$%02X\n",
                       name, t, i, ref_mem[i], mem[i]);
                (*printed)++;
            }
    }

    /* The hardware trace, compared as a SEQUENCE.  Order is semantic: the last write to a
       given ULA palette slot is the one that shows, and $FE66 is what closes a band record.
       An overflow on either side is reported rather than truncated silently. */
    if (g_hwLogN != ref_hw_n || g_hwLogOverflow != ref_hw_ovf) {
        failed = 1;
        if (*printed < 12) {
            printf("[HW DIFF] %s case %d  write count ref=%u native=%u (overflow ref=%u native=%u)\n",
                   name, t, ref_hw_n, g_hwLogN, ref_hw_ovf, g_hwLogOverflow);
            (*printed)++;
        }
    } else {
        for (unsigned i = 0; i < ref_hw_n; i++)
            if (g_hwLogAddr[i] != ref_hw_addr[i] || g_hwLogVal[i] != ref_hw_val[i]) {
                failed = 1;
                if (*printed < 12) {
                    printf("[HW DIFF] %s case %d  write %u  ref=$%04X<-$%02X native=$%04X<-$%02X\n",
                           name, t, i, ref_hw_addr[i], ref_hw_val[i], g_hwLogAddr[i], g_hwLogVal[i]);
                    (*printed)++;
                }
                break;
            }
    }

    /* ⭐ THE SMC TRAP is a third output channel, and the same argument as the hardware
       trace applies: a twin that traps at a different site, on a different value, or a
       different number of times has diverged even when mem[] agrees.  Compared here so
       no fixture has to remember to. */
    if (g_smcUnhandled - smc_before != ref_smc_n ||
        (ref_smc_n && (g_smcSite != ref_smc_site || g_smcValue != ref_smc_value))) {
        failed = 1;
        if (*printed < 12) {
            printf("[SMC DIFF] %s case %d  traps ref=%lu native=%lu  last ref=$%04X<-$%04X "
                   "native=$%04X<-$%04X\n", name, t, ref_smc_n,
                   g_smcUnhandled - smc_before, ref_smc_site, ref_smc_value,
                   g_smcSite, g_smcValue);
            (*printed)++;
        }
    }

    /* Declared-live registers are part of the contract — a diff is a failure. */
#define CHECK_REG(bit, field, label)                                              \
    if ((liveMask & (bit)) && cpu.field != ref_cpu.field) {                       \
        failed = 1;                                                              \
        if (*printed < 12) {                                                     \
            printf("[REG DIFF] %s case %d  %s  ref=$%02X native=$%02X (declared live)\n", \
                   name, t, label, ref_cpu.field, cpu.field); (*printed)++;      \
        }                                                                        \
    }
    CHECK_REG(LIVE_A, A, "A")
    CHECK_REG(LIVE_X, X, "X")
    CHECK_REG(LIVE_Y, Y, "Y")
    CHECK_REG(LIVE_S, S, "S")
#undef CHECK_REG
    if ((liveMask & LIVE_FLAGS) &&
        (cpu.N != ref_cpu.N || cpu.V != ref_cpu.V || cpu.Z != ref_cpu.Z || cpu.C != ref_cpu.C)) {
        failed = 1;
        if (*printed < 12) {
            printf("[REG DIFF] %s case %d  flags NVZC ref=%d%d%d%d native=%d%d%d%d (declared live)\n",
                   name, t, ref_cpu.N, ref_cpu.V, ref_cpu.Z, ref_cpu.C,
                   cpu.N, cpu.V, cpu.Z, cpu.C);
            (*printed)++;
        }
    }
    return failed;
}

/* Generic fixture: randomised whole-mem[] contract test with an explicit live-exit-
   register declaration.  Fits any leaf observed purely through mem[] plus the registers
   it declares.  Anything more specific (a restricted input domain, a stack-aware leaf)
   gets its own test_<name>() — but it still calls diff_run and still declares liveMask. */
static int test_contract(const char* name, void (*native)(void), void (*t6502)(void),
                         unsigned liveMask, int cases)
{
    register_fixture(name);
    if (!want(name)) return 0;
    static uint8_t pre[65536];
    int fail = 0, printed = 0;
    for (int t = 0; t < cases; t++) {
        fill_random(pre);
        fail += diff_run(name, pre, zero_cpu(), native, t6502, liveMask, t, &printed);
    }
    printf("%-32s %7d cases, %d mismatch (must be 0)  live=%s%s%s%s%s\n",
           name, cases, fail,
           (liveMask & LIVE_A) ? "A" : "", (liveMask & LIVE_X) ? "X" : "",
           (liveMask & LIVE_Y) ? "Y" : "", (liveMask & LIVE_S) ? "S" : "",
           (liveMask == LIVE_NONE) ? "none" : ((liveMask & LIVE_FLAGS) ? "+flags" : ""));
    return fail;
}

/* ==========================================================================
   FIXTURES
   ==========================================================================
   ⚠ Registering the function in transpile.py's VALIDATE_FUNCS is only HALF the job:
   without a fixture here, check_coverage() now fails the run rather than letting a
   vacuous PASS through.  That is deliberate.
   ========================================================================== */

void platform_test_t1_pending(int on);
void irq1v_band_schedule(void);
void irq1v_band_schedule__t6502(void);

/* --------------------------------------------------------------------------
   $4E5C irq1v_band_schedule — the raster-band state machine (src/gen/revs_native.c).

   Not test_contract(), for three reasons, each of which is the fixture's actual content:

   1. THE GATING READ IS NOT IN mem[].  The handler's first act is `LDA $FE6D / AND #$40`,
      and a clear bit sends it straight out to the MOS's handler.  fill_random() cannot
      reach that bit — it is the platform's.  Both polarities are exercised here, and the
      chain-out one gets its own small pass because its exit register contract is DIFFERENT
      (it leaves through a JMP, so nothing restores A).

   2. THE BAND COUNTER MUST BE STEERED.  $4F43 selects one of five arms plus two
      do-nothing paths.  A uniformly random byte would spend 251/256 of its cases on
      "negative and not $FF", i.e. on the arm that does nothing — 4000 cases of proving
      that a `goto rti` is a `goto rti`.  Each path gets its own budget instead.

   3. THE HORIZON SPLIT IS THE INTERESTING INPUT, and it is two bytes.  Band 1's arm
      falls THROUGH into band 2 (and band 2 into band 3) when the split underflows, so
      $4F1F/$4F20 decide the control flow.  Random 16-bit values put ~90% of cases on
      one side of `$153C`, so the fixture also pins the boundary explicitly.

   ⚠ WHAT IS AND IS NOT COVERED, stated rather than quietly skipped.  Band 4 calls
   tick_wheel_spin — the cycle's only game work — and it really runs here, on randomised memory:
   deleting the call fails 128 of 128 cases.  What the differential canNOT see is the
   register hand-off INTO it: A, X and N/Z/C can each be falsified at the call site with
   no observable effect, because the body reloads them.  That part of the twin is
   faithful-by-construction, not proven, and the comment at the call site says so.

   ⭐ SABOTAGE RECORD (2026-08-16), because a first-run PASS is not evidence.  Nine
   deliberate defects: horizon remainder +1, X not restored, band counter not advanced,
   the horizon boundary <= → <, band-3 latch +1, band-3 palette 3 entries instead of 4,
   band-0 palette written in ascending order, the $FE69 poke dropped, tick_wheel_spin not called.
   All nine fail now.  ⚠⚠ FOUR OF THEM PASSED before diff_run grew a hardware trace: the
   ULA and the T1 latch are not in mem[] and this routine leaves only four bytes there, so
   a mem[]-only differential was validating almost none of its output.
   -------------------------------------------------------------------------- */
static int irq1v_case(const char* label, int state, int pending, int cases,
                      int pinSplit, unsigned split, int* printed)
{
    static uint8_t pre[65536];
    unsigned liveMask = LIVE_A | LIVE_X | LIVE_Y | LIVE_S | LIVE_FLAGS;
    int fail = 0, t;

    platform_test_t1_pending(pending);
    for (t = 0; t < cases; t++) {
        Cpu6502 c = zero_cpu();
        fill_random(pre);
        pre[0x4F43] = (uint8_t)state;
        if (pinSplit) { pre[0x4F1F] = (uint8_t)split; pre[0x4F20] = (uint8_t)(split >> 8); }
        /* A real IRQ arrives with the foreground's registers live and S well inside the
           stack page (measured mid-race on a BBC: $F2).  Randomising them is what makes
           "A, X and Y come back unchanged" a tested contract instead of 0 == 0. */
        c.A = (uint8_t)xs(); c.X = (uint8_t)xs(); c.Y = (uint8_t)xs();
        c.S = (uint8_t)(0xC0 + (xs() & 0x3F));
        c.N = xs() & 1; c.V = xs() & 1; c.Z = xs() & 1;
        c.C = xs() & 1; c.I = xs() & 1; c.D = xs() & 1;
        fail += diff_run(label, pre, c, irq1v_band_schedule, irq1v_band_schedule__t6502,
                         liveMask, t, printed);
    }
    platform_test_t1_pending(0);
    return fail;
}

static int test_irq1v_band_schedule(void)
{
    int fail = 0, printed = 0;
    register_fixture("irq1v_band_schedule");
    if (!want("irq1v_band_schedule")) return 0;

    /* not our interrupt: chain on to the saved IRQ1V.  A is left 0 by the AND. */
    fail += irq1v_case("irq1v:chain",  0x00, 0, 2000, 0, 0, &printed);

    fail += irq1v_case("irq1v:band0",  0x00, 1, 4000, 0, 0, &printed);
    /* band 1 both sides of the $153C horizon split, plus the two boundary values */
    fail += irq1v_case("irq1v:band1",  0x01, 1, 4000, 0, 0,      &printed);
    fail += irq1v_case("irq1v:band1<", 0x01, 1,  500, 1, 0x153B, &printed);
    fail += irq1v_case("irq1v:band1=", 0x01, 1,  500, 1, 0x153C, &printed);
    fail += irq1v_case("irq1v:band1>", 0x01, 1,  500, 1, 0x153D, &printed);
    fail += irq1v_case("irq1v:band2",  0x02, 1, 4000, 0, 0, &printed);
    fail += irq1v_case("irq1v:band3",  0x03, 1, 4000, 0, 0, &printed);
    fail += irq1v_case("irq1v:wrap",   0xFF, 1, 2000, 0, 0, &printed);
    fail += irq1v_case("irq1v:idle",   0x80, 1, 2000, 0, 0, &printed);
    fail += irq1v_case("irq1v:idle2",  0xC3, 1, 2000, 0, 0, &printed);
    /* every state above 3 takes band 4's arm; $04 and a high one both prove it */
    fail += irq1v_case("irq1v:band4",  0x04, 1,   64, 0, 0, &printed);
    fail += irq1v_case("irq1v:band4b", 0x7F, 1,   64, 0, 0, &printed);

    printf("%-32s %7d cases, %d mismatch (must be 0)  live=AXYS+flags\n",
           "irq1v_band_schedule", 25628, fail);
    return fail;
}

void view_paint_lines(void);
void view_paint_lines__t6502(void);
extern unsigned long g_viewTableCollisions;   /* asserted below; see revs_native.c */

/* --------------------------------------------------------------------------
   $7BE2 view_paint_lines — the 40-unit column chain (src/gen/revs_native.c).

   ⚠⚠ fill_random() ALONE CANNOT TEST THIS ROUTINE, and the reason is the point of the
   fixture.  The chain is self-modifying code: forty `STA (zp),Y` opcode slots that are
   switched between $91 and $60, three `JSR` operands and three store operands that are
   rewritten with a computed low byte, and one terminator at $7EEE that toggles $E0/$60.
   A uniformly random byte in any of those is neither legal value, so the FIRST thing both
   models do is trap through platform_smc_unhandled — agreeing with each other about
   nothing.  So the pre-state is BUILT: random everywhere, legal where the operand
   encoding says it must be.

   WHERE EACH CONSTRAINT COMES FROM — every one is read off the code, none is a guess:

     * the 29 reachable opcode slots start as `STA` ($91) and $7EEE as `CPX` ($E0),
       because $7BBF restores exactly those on the way out of every real call;
     * the fixed HIGH operand byte of each patched store/call is what pins it to one
       page ($7C for chain A, $7E for chain B), so those bytes are set, not randomised;
     * $3150,X names a chain-A opcode slot, so it is one of the fifteen $0F+$11k lows;
     * $30D0,X names a chain-B ENTRY, so it is one of the twenty-eight unit / unit+$05
       lows in page $7E;
     * $3080,X names a chain-B opcode slot AND, through `$F1 - it`, chain A's entry —
       and $F1 - ($0F+$11k) is exactly $11*(13-k)+5, so ONE value satisfies both.  That
       identity is why the table can serve both purposes at all.

   ⭐ AND THE MEMORY MAP FALLS OUT OF IT.  Each $80-spaced block holds $50 source bytes
   (one per column, X = $03..$4F) and $30 spare; every control table above lives in a
   spare — $3050/$3080/$30D0/$3150, $3350, $33D0, $38D0, $38FC, $3950.  The one
   exception is $3080,X for phase 3's columns X = $03..$1B, which IS unit 1's source
   range, and that is consistent rather than a clash: phase 3 enters chain A at unit
   13-k, so units 0 and 1 are never drawn for those columns and their source bytes are
   free.  It also bounds the fixture: k <= 11 keeps the entry at unit 2 or below, and a
   larger k would have the chain zero $3080,X between its two reads.  Both models then
   trap identically — the "illegal" case below proves that rather than assuming it.

   ⭐ SABOTAGE RECORD (2026-08-16) — thirteen deliberate defects, all caught:
   the dirty source not cleared (700/700), a planted RTS ignored (508 + the trap count
   moved 196 → 314), the row offset off by one cell (700), chain B storing through $70
   (700), the sweep terminator off by one (700), the restore dropping chain B's un-plant
   (602), the carry into $73 lost in the advance (700) and again in phase 3 (656), the
   forced entry taking the dirty test anyway (697), phase 2 not arming $7EEE (701), the
   background byte from the wrong table (387), the unpatchable page-$7D slots dispatched
   as if they were patchable (701), and — caught by NOTHING BUT THE FLAG COMPARISON — the
   $7EF3 pointer advance written as plain C instead of the ADC macros (11 cases, V only).
   ⚠ That last one is why the flags are declared live: V and C are the two the chain can
   leak, and they only become visible when a trap cuts the driver short before its own
   `SBC` overwrites them.  ⚠⚠ And sabotage #7 first reported #6's number because its patch
   had failed to apply and `make` had nothing to rebuild — a stale object reading as a
   result, for the second time on this project.  Every sabotage must change the source.

   TWO INPUT SHAPES, because the real one is not the random one.  With random sources
   ~255 of every 256 units are dirty; the measured sweep is 96% CLEAN (2093 units, ~83
   stores — docs/direct-bitplane-plan.md §7a), and a clean unit is the path where A
   carries down the column from the cell above.  The `sparse` cases put the sources back
   at roughly that density so that path is the one under test.
   -------------------------------------------------------------------------- */
enum { DASH_SLOT_N = 15, DASH_ENTRYB_N = 28 };

static void dash_pre(uint8_t* pre, int sparse, int illegal)
{
    /* the fifteen chain-A opcode-slot low bytes; chain B uses the first fourteen */
    uint8_t slotLow[DASH_SLOT_N];
    uint8_t entryB[DASH_ENTRYB_N];
    int k, x;

    for (k = 0; k < DASH_SLOT_N; k++)   slotLow[k] = (uint8_t)(0x0F + 0x11 * k);
    for (k = 0; k < 14; k++) { entryB[2*k] = (uint8_t)(0x11 * k);
                               entryB[2*k+1] = (uint8_t)(0x11 * k + 5); }

    fill_random(pre);

    /* the source blocks: dense by default, ~1 in 20 non-zero for the measured shape */
    if (sparse)
        for (k = 0; k < 40; k++)
            for (x = 0; x < 0x50; x++)
                if (xs() % 20) pre[0x3000 + 0x80 * k + x] = 0;

    /* every reachable opcode slot unpatched, and the sweep's terminator armed */
    for (k = 0; k < 15; k++) pre[0x7C0F + 0x11 * k] = 0x91;
    for (k = 0; k < 14; k++) pre[0x7E0F + 0x11 * k] = 0x91;
    pre[0x7EEE] = 0xE0;

    /* the fixed high operand bytes — what pins each writer to one page */
    pre[0x7BD5] = 0x7C; pre[0x7BD8] = 0x7C; pre[0x7BDB] = 0x7E;
    pre[0x7D25] = 0x7C; pre[0x7D30] = 0x7C; pre[0x7D4E] = 0x7E;
    pre[0x7F25] = 0x7C; pre[0x7F30] = 0x7C; pre[0x7F69] = 0x7C;
    pre[0x7F7E] = 0x7E; pre[0x7F89] = 0x7E; pre[0x7F9C] = 0x7E;

    /* the three "where did I last plant" records, and the chain-B call operand that is
       reused verbatim when a column's plant is skipped */
    pre[0x7D24] = slotLow[xs() % DASH_SLOT_N];
    pre[0x7F24] = slotLow[xs() % DASH_SLOT_N];
    pre[0x7F7D] = slotLow[xs() % 14];
    pre[0x7D4D] = entryB[xs() % DASH_ENTRYB_N];

    /* the per-scan-line control tables */
    for (x = 0x03; x <= 0x2B; x++) {
        pre[0x3150 + x] = slotLow[xs() % DASH_SLOT_N];
        pre[0x30D0 + x] = entryB[xs() % DASH_ENTRYB_N];
    }
    for (x = 0x03; x <= 0x1B; x++)
        pre[0x3080 + x] = (uint8_t)(0x0F + 0x11 * (xs() % 12));

    /* one column given a low byte that is not a unit boundary: both models must trap at
       the same site with the same value and unwind the same way */
    if (illegal) pre[0x30D0 + 0x03 + (xs() % 0x29)] = 0x08;
}

static int test_view_paint_lines(void)
{
    static uint8_t pre[65536];
    unsigned liveMask = LIVE_A | LIVE_X | LIVE_Y | LIVE_S | LIVE_FLAGS;
    unsigned long smcLegal, smcIllegal;
    int fail = 0, printed = 0, t;
    const int dense = 300, sparse = 300, illegal = 100;

    register_fixture("view_paint_lines");
    if (!want("view_paint_lines")) return 0;

    /* The trap path is real code in BOTH models and has to unwind identically, so it gets
       tested rather than avoided — which means Platform::smcUnhandled must count instead of
       abort.  The counter is then asserted below, both directions: zero over the legal
       cases (a pre-state that traps at once would compare nothing) and non-zero over the
       illegal ones (or they are not testing what they claim). */
    setenv("REVS_SMC_CONTINUE", "1", 1);
    g_smcUnhandled = 0;

    for (t = 0; t < dense + sparse; t++) {
        Cpu6502 c = zero_cpu();
        dash_pre(pre, t >= dense, 0);
        c.A = (uint8_t)xs(); c.X = (uint8_t)xs(); c.Y = (uint8_t)xs();
        c.S = (uint8_t)(0xC0 + (xs() & 0x3F));
        c.N = xs() & 1; c.V = xs() & 1; c.Z = xs() & 1; c.C = xs() & 1; c.I = xs() & 1;
        /* ⚠ D IS NOT RANDOMISED, and the reason is a real finding rather than convenience:
           $7F51's `SEC / SBC $3080,X` is BCD in decimal mode, and $F1 - $97 then computes
           $54 instead of $5A — a low byte that is not a unit boundary, so BOTH models trap
           and the case tests the trap instead of the sweep.  The 6502 never runs this in
           decimal mode (the MOS clears D on reset and every IRQ entry CLDs), and both
           models go through the same SBC macro, so nothing is being papered over. */
        c.D = 0;
        fail += diff_run("view_paint_lines", pre, c,
                         view_paint_lines, view_paint_lines__t6502, liveMask, t, &printed);
    }
    smcLegal = g_smcUnhandled;

    for (t = dense + sparse; t < dense + sparse + illegal; t++) {
        Cpu6502 c = zero_cpu();
        dash_pre(pre, t & 1, 1);
        c.A = (uint8_t)xs(); c.X = (uint8_t)xs(); c.Y = (uint8_t)xs();
        c.S = (uint8_t)(0xC0 + (xs() & 0x3F));
        c.N = xs() & 1; c.V = xs() & 1; c.Z = xs() & 1; c.C = xs() & 1; c.I = xs() & 1;
        c.D = 0;
        fail += diff_run("view_paint_lines", pre, c,
                         view_paint_lines, view_paint_lines__t6502, liveMask, t, &printed);
    }
    smcIllegal = g_smcUnhandled - smcLegal;
    unsetenv("REVS_SMC_CONTINUE");

    if (smcLegal != 0) {
        printf("[VACUOUS] view_paint_lines: %lu SMC traps over the %d LEGAL cases — the "
               "pre-state is not a legal overlay state, so those cases compared little\n",
               smcLegal, dense + sparse);
        fail++;
    }
    if (smcIllegal == 0) {
        printf("[VACUOUS] view_paint_lines: 0 SMC traps over the %d ILLEGAL cases — the "
               "trap path was never reached\n", illegal);
        fail++;
    }
    /* The twin answers "is this address a unit / a unit+$05 / an opcode slot" out of two
       256-byte tables instead of the oracle's forty-entry search, which is only equivalent
       while no address means two things.  The twin counts every clash as it builds them; a
       counter nobody reads is not a safeguard, so the harness asserts it. */
    if (g_viewTableCollisions != 0) {
        printf("[BROKEN] view_paint_lines: %lu address-table collisions — a unit start and "
               "another unit's +$05 (or slot) share an address, so the one-answer lookup is "
               "not equivalent to the oracle's first-match search\n", g_viewTableCollisions);
        fail++;
    }
    printf("%-32s %7d cases, %d mismatch (must be 0)  live=AXYS+flags  "
           "(%lu traps in %d illegal cases)\n",
           "view_paint_lines", dense + sparse + illegal, fail, smcIllegal, illegal);
    return fail;
}

/* ==========================================================================
   $24F6 build_track_geometry and $1A20 draw_road — THE VIEW PIPELINE'S PRODUCERS
   --------------------------------------------------------------------------
   Both are short DRIVERS over long transliterated subtrees (road_edge_start / road_edge_walk
   / project_point, and fill_line_attr / draw_surface_spans / mark_line_surfaces /
   interp_edge), so a randomised pre-state exercises far more code than the twin itself —
   which is the point: the twin's whole job is to hand those callees the same registers, in
   the same order, off the same cells.  A wrong argument shows up as a mem[] avalanche.

   ⚠ build_track_geometry is SELF-MODIFYING at $2538 and $2542, and both sites are EXITS on
   an unrecognised byte.  Random bytes there would trap in almost every case and compare
   almost nothing, so the instruction shapes are planted: Silverstone's own bytes, an
   expansion circuit's `JSR <hook>` rewrite, and — deliberately — garbage, so the trap path
   is tested rather than avoided.
   ========================================================================== */
void build_track_geometry(void);
void build_track_geometry__t6502(void);
void draw_road(void);
void draw_road__t6502(void);

enum { GEO_SILVERSTONE = 0, GEO_HOOKED = 1, GEO_GARBAGE = 2 };

/* ⭐⭐ AND THE SECOND THING: the geometry subtree is self-modifying too, and a random byte at
   one of ITS sites is not a hang but an EXIT — road_edge_start traps at $231A and returns
   without ever reaching the projection loop, so horizon_extent comes back 0 and the whole
   horizon half of build_track_geometry is never exercised.  (Measured: extent was $00 in
   every case of the first attempt, and two sabotages passed because of it.)  These are the
   disassembly's own bytes for the sites road_edge_start / road_edge_walk dispatch on. */
static void plant_geometry_smc(uint8_t* pre)
{
    pre[0x231A] = 0xF0; pre[0x231B] = 0x0F;                      /* BEQ $232B */
    pre[0x248B] = 0xB0; pre[0x248C] = 0x2B;                      /* BCS $24B8 */
    pre[0x248D] = 0x4C;                                          /* JMP $2403 */
    pre[0x24DE] = 0x20; pre[0x24DF] = 0xF3; pre[0x24E0] = 0x12;  /* JSR $12F3 */
    pre[0x24E9] = 0xC9; pre[0x24EA] = 0x0E;                      /* CMP #$0E  */
    pre[0x24F2] = 0x20; pre[0x24F3] = 0x0B; pre[0x24F4] = 0x14;  /* JSR $140B */
}

/* ⭐ THE ONE THING A RANDOM PRE-STATE MUST NOT BE ALLOWED TO DO, and it is not about these
   twins: the span plotters at $2C00-$2FFF are self-modifying CHAINS whose backward branch
   offsets they load out of the tables at $3E50 and $40D0 ($2D17/$2D9A: `LDA table,X / STA
   <branch operand>`).  A random byte there is a branch to ITSELF — the oracle spins forever
   inside FUN_2d17 and the harness never returns.  (Found by sampling a hung run, not by
   reading: case 5 of the first draw_road attempt.)  Both offset tables are therefore planted
   with $00, i.e. "run the chain from the top", which is legal by construction: every target
   is forward, so every chain terminates.  Everything else stays random — the plotters are
   identical code in both models and are not what these fixtures compare. */
static void plant_plotter_chains(uint8_t* pre)
{
    memset(pre + 0x3E50, 0x00, 0x100);
    memset(pre + 0x40D0, 0x00, 0x100);
}

static void geometry_pre(uint8_t* pre, int shape)
{
    fill_random(pre);
    plant_plotter_chains(pre);

    plant_geometry_smc(pre);
    /* ⭐ BOUNDARY STEERING, and both halves of it are load-bearing:

       horizon_index reaches the twin's own arithmetic straight out of the pre-state, so its
       two boundaries ($28, where the wrap fires, and $4F, where the extent is clamped) are
       drawn explicitly rather than left to 1-in-256 luck.  A uniform byte let an off-by-one
       wrap threshold PASS 400 cases.

       horizon_index_prev is held to 0..8 in a third of the cases because road_edge_start
       clamps the extent down to 7 whenever it is larger ($23B2) — with a uniform byte that
       happens 248 times in 256 and the extent is 7 in every single case, which is what hid
       the $4F clamp and the second edge_y store. */
    { static const uint8_t edge[] = { 0x00, 0x27, 0x28, 0x29, 0x4E, 0x4F, 0x50, 0xFF };
      pre[0x51] = edge[xs() % (sizeof edge)];
      if (xs() % 3 == 0) pre[0x52] = (uint8_t)(xs() % 9); }
    if (shape == GEO_SILVERSTONE) {
        pre[0x2538] = 0x99; pre[0x2539] = 0x48; pre[0x253A] = 0x5F;  /* STA $5F48,Y */
        pre[0x2542] = 0x20; pre[0x2543] = 0x50; pre[0x2544] = 0x34;  /* JSR abs8    */
        pre[0x2545] = 0x4A;                                          /* LSR A       */
    } else if (shape == GEO_HOOKED) {
        /* what an expansion circuit's ModifyGameCode leaves behind: a call into its own
           hook block in place of each site, and a NOP where the LSR was */
        pre[0x2538] = 0x20; pre[0x2539] = 0x22; pre[0x253A] = 0x5A;  /* JSR $5A22 */
        pre[0x2542] = 0x20; pre[0x2543] = 0x50; pre[0x2544] = 0x34;
        pre[0x2545] = 0xEA;
    }
    /* GEO_GARBAGE: whatever fill_random left — the trap arms */
}

/* $253B-$2549 recomputed from the POST state, which is the only end-to-end proof that the
   twin reached its tail: nothing but the tail writes horizon_half_width, and nothing writes
   the edge arrays after it reads them. */
static int geometry_tail_ran(const uint8_t* post)
{
    unsigned p    = post[0x0052];                       /* horizon_index_prev = the point */
    unsigned diff = (post[0x5E90 + p] - post[0x5EB8 + p]) & 0xFF;
    if (diff & 0x80) diff = (diff ^ 0xFF) + 1;          /* abs8 */
    return post[0x62FC] == (uint8_t)((diff & 0xFF) >> 1);
}

static int test_view_producers(void)
{
    static uint8_t pre[65536];
    unsigned liveMask = LIVE_A | LIVE_X | LIVE_Y | LIVE_S | LIVE_FLAGS;
    int fail = 0, printed = 0, t;
    /* ⚠ The case counts are SMALL by the standards of the other fixtures (twin #2 runs 700)
       and the reason is measured, not arbitrary: a randomised pre-state sends the span walks
       into their worst case, so one case here costs milliseconds rather than microseconds.
       $REVS_VALIDATE_CASES scales all four for a deeper soak. */
    int scale = 1;
    { const char* e = getenv("REVS_VALIDATE_CASES"); if (e) scale = atoi(e); }
    if (scale < 1) scale = 1;
    const int legal = 200 * scale, hooked = 100 * scale, garbage = 100 * scale,
              road = 200 * scale;
    int tailRan = 0;

    register_fixture("build_track_geometry");
    register_fixture("draw_road");
    setenv("REVS_SMC_CONTINUE", "1", 1);

    if (want("build_track_geometry")) {
        for (t = 0; t < legal + hooked + garbage; t++) {
            int shape = t < legal ? GEO_SILVERSTONE
                      : t < legal + hooked ? GEO_HOOKED : GEO_GARBAGE;
            Cpu6502 c = zero_cpu();
            geometry_pre(pre, shape);
            c.A = (uint8_t)xs(); c.X = (uint8_t)xs(); c.Y = (uint8_t)xs();
            c.N = xs() & 1; c.V = xs() & 1; c.Z = xs() & 1; c.C = xs() & 1;
            c.D = 0;   /* the 6502 never runs the engine in decimal mode — see twin #2 */
            fail += diff_run("build_track_geometry", pre, c, build_track_geometry,
                             build_track_geometry__t6502, liveMask, t, &printed);
            if (shape == GEO_SILVERSTONE && geometry_tail_ran((const uint8_t*)mem)) tailRan++;
        }
        if (tailRan == 0) {
            printf("[VACUOUS] build_track_geometry: not one of the %d Silverstone cases "
                   "reached the horizon_half_width tail — the SMC arm exited first\n", legal);
            fail++;
        }
        printf("%-32s %7d cases, %d mismatch (must be 0)  live=AXY+flags  "
               "(%d/%d reached the tail)\n", "build_track_geometry",
               legal + hooked + garbage, fail, tailRan, legal);
    }

    if (want("draw_road")) {
        int roadFail = 0;
        for (t = 0; t < road; t++) {
            Cpu6502 c = zero_cpu();
            fill_random(pre);
            plant_plotter_chains(pre);
            c.A = (uint8_t)xs(); c.X = (uint8_t)xs(); c.Y = (uint8_t)xs();
            c.N = xs() & 1; c.V = xs() & 1; c.Z = xs() & 1; c.C = xs() & 1;
            c.D = 0;
            roadFail += diff_run("draw_road", pre, c, draw_road, draw_road__t6502,
                                 liveMask, t, &printed);
        }
        fail += roadFail;
        printf("%-32s %7d cases, %d mismatch (must be 0)  live=AXY+flags\n",
               "draw_road", road, roadFail);
    }

    unsetenv("REVS_SMC_CONTINUE");
    return fail;
}

/* ==========================================================================
   $46A1 apply_driving_model, $2AD1 draw_track_object, $1E15 fill_dash_edge_columns
   --------------------------------------------------------------------------
   The body's three remaining SHORT DRIVERS.  Like the view producers above, each one is a
   handful of instructions over a long transliterated subtree, so a randomised pre-state
   exercises far more code than the twin — and that is the point: the twin's job is to hand
   its callees the same registers off the same cells in the same order.

   ⭐ NONE OF THE THREE HAS A SELF-MODIFYING SITE OF ITS OWN, so there are no trap arms to
   test here.  What the pre-state has to do instead is stop the CALLEES from trapping, because
   an SMC trap is an early RETURN in both models and a returned-early pair compares almost
   nothing.  Three sites are reachable and all three are planted with Silverstone's own bytes:
   $1FE9 inside plot_object, and $44D5 / $45CB inside the last sub-model of the driving chain.
   ========================================================================== */
void apply_driving_model(void);
void apply_driving_model__t6502(void);
void draw_track_object(void);
void draw_track_object__t6502(void);
void fill_dash_edge_columns(void);
void fill_dash_edge_columns__t6502(void);

#define PRE_CAR_FLAGS_1   0x018C
#define PRE_OBJECT_POS_LO 0x0380
#define PRE_OBJECT_POS_HI 0x0398

static void plant_body_driver_smc(uint8_t* pre)
{
    pre[0x1FE9] = 0xA6;                       /* LDX horizon_extent — plot_object   */
    pre[0x44D5] = 0xB9;                       /* LDA abs,Y         — the $44EA tail */
    pre[0x45CB] = 0x0A; pre[0x45CC] = 0x26;   /* ASL A / ROL $77   — likewise       */
}

/* $46B8-$46CD recomputed from the POST state: road_speed and road_speed_frac have exactly
   ONE writer each in the whole engine ($46C0 and $46C4) and wheel_spin_rate's other two
   writers are not in this subtree, so this relation holding is proof the routine reached
   the speed split rather than exiting in a callee. */
static int speed_split_ran(const uint8_t* post)
{
    unsigned want = post[0x0063] ? post[0x0063] : (unsigned)(post[0x002E] & 0xF0);
    return post[0x0000] == want;
}

/* The four cells the object plotter is driven through, recomputed from the PRE state — the
   twin's whole output on the drawn path.  plot_object rewrites plot_width ($1FF4) and $2B but
   never plot_row / plot_column / plot_shape, which is why only those three are checked. */
static int object_block_ran(const uint8_t* pre, const uint8_t* post, uint8_t slot)
{
    unsigned lo   = (pre[PRE_OBJECT_POS_LO + slot] - pre[0x000A]) & 0x1FF;
    unsigned hi   = (pre[PRE_OBJECT_POS_HI + slot] - pre[0x000B] - (lo > 0xFF ? 1 : 0)) & 0xFF;
    unsigned row  = ((hi << 8) | (lo & 0xFF)) << 2;
    return post[0x0037] == (pre[PRE_CAR_FLAGS_1 + slot] & 0x0F)
        && post[0x0035] == (uint8_t)(((row >> 8) & 0xFF) + 0x50)
        && post[0x0036] == pre[0x03B0 + slot];
}

/* Which of draw_track_object's three paths a case takes, decided from the PRE state: nothing
   the routine calls writes car_flags_1, object_pos or player_pos before the test. */
enum { OBJ_EMPTY = 0, OBJ_OFFSCREEN = 1, OBJ_DRAWN = 2 };
static int object_path(const uint8_t* pre, uint8_t slot)
{
    if (pre[PRE_CAR_FLAGS_1 + slot] & 0x80) return OBJ_EMPTY;
    unsigned lo = (pre[PRE_OBJECT_POS_LO + slot] - pre[0x000A]) & 0x1FF;
    unsigned hi = (pre[PRE_OBJECT_POS_HI + slot] - pre[0x000B] - (lo > 0xFF ? 1 : 0)) & 0xFF;
    if (hi & 0x80) return hi >= 0xE0 ? OBJ_DRAWN : OBJ_OFFSCREEN;
    return hi < 0x20 ? OBJ_DRAWN : OBJ_OFFSCREEN;
}

/* Both of fill_dash_edge_columns' passes ran to completion: plot_ptr2 still holds the SECOND
   boundary table, and fill_edge_column_run's own two cells stopped where the second run's
   arguments said they would ($42 is the limit it was handed, $85 the column it stopped at). */
static int edge_columns_ran(const uint8_t* post)
{
    return post[0x0072] == 0x00 && post[0x0073] == 0x44
        && post[0x0042] == 0x22 && post[0x0085] == 0x22;
}

static int test_body_drivers(void)
{
    static uint8_t pre[65536];
    unsigned liveMask = LIVE_A | LIVE_X | LIVE_Y | LIVE_S | LIVE_FLAGS;
    int fail = 0, printed = 0, t;
    int scale = 1;
    { const char* e = getenv("REVS_VALIDATE_CASES"); if (e) scale = atoi(e); }
    if (scale < 1) scale = 1;
    const int model = 200 * scale, object = 300 * scale, edges = 600 * scale;

    register_fixture("apply_driving_model");
    register_fixture("draw_track_object");
    register_fixture("fill_dash_edge_columns");
    setenv("REVS_SMC_CONTINUE", "1", 1);

    if (want("apply_driving_model")) {
        int subFail = 0, splitRan = 0, offPower = 0, onPower = 0;
        for (t = 0; t < model; t++) {
            Cpu6502 c = zero_cpu();
            fill_random(pre);
            plant_plotter_chains(pre);
            plant_body_driver_smc(pre);
            /* ⭐ STEERED, and the reason is the twin's only branch: drive_state decides
               whether model_state elements 5..7 are zeroed, and it is compared against 2.
               A uniform byte takes the >= 2 arm 254 times in 256, so the ONE case that
               matters — a car under power — would be luck.  The three values the engine
               itself writes are 0, 1 and $7F. */
            { static const uint8_t st[] = { 0x00, 0x01, 0x02, 0x7F };
              pre[0x002D] = st[xs() % (sizeof st)]; }
            if (pre[0x002D] >= 2) offPower++; else onPower++;
            c.A = (uint8_t)xs(); c.X = (uint8_t)xs(); c.Y = (uint8_t)xs();
            c.N = xs() & 1; c.V = xs() & 1; c.Z = xs() & 1; c.C = xs() & 1;
            c.D = 0;   /* the 6502 never runs the engine in decimal mode — see twin #2 */
            subFail += diff_run("apply_driving_model", pre, c, apply_driving_model,
                                apply_driving_model__t6502, liveMask, t, &printed);
            if (speed_split_ran((const uint8_t*)mem)) splitRan++;
        }
        fail += subFail;
        if (splitRan == 0) {
            printf("[VACUOUS] apply_driving_model: not one of %d cases reached the speed "
                   "split — a callee trapped out first\n", model);
            fail++;
        }
        if (offPower == 0 || onPower == 0) {
            printf("[VACUOUS] apply_driving_model: the drive_state branch went only one way "
                   "(%d off power, %d on)\n", offPower, onPower);
            fail++;
        }
        printf("%-32s %7d cases, %d mismatch (must be 0)  live=AXY+flags  "
               "(%d reached the speed split, %d/%d off power)\n", "apply_driving_model",
               model, subFail, splitRan, offPower, model);
    }

    if (want("draw_track_object")) {
        int subFail = 0, paths[3] = { 0, 0, 0 }, blockRan = 0;
        for (t = 0; t < object; t++) {
            Cpu6502 c = zero_cpu();
            fill_random(pre);
            plant_plotter_chains(pre);
            plant_body_driver_smc(pre);
            uint8_t slot = (uint8_t)(xs() % 24);   /* the 24 real object slots */
            /* Two thirds of the cases get an OCCUPIED slot: a uniform flag byte is empty
               half the time, and the empty path is three instructions long. */
            if (xs() % 3) pre[PRE_CAR_FLAGS_1 + slot] &= 0x7F;
            /* ⭐⭐ AND SHAPE 9 IS EXCLUDED, WHICH IS NOT A CONVENIENCE.  plot_object's outer
               loop at $2002-$2027 repeats while $62F3 came back as 9 and mem[$0025] is
               positive, and $62F3 is re-stored from plot_shape at the top of every pass — so
               with plot_shape == 9 the pass is IDENTICAL each time round and the only way out
               is FUN_202a returning carry set.  On the real shape tables it does; on random
               bytes it need not, and the ORACLE spins forever with the twin never reached.
               (Found by sampling a 12-minute run, the same way the plotter chains were.)
               $0025 has exactly one writer in the engine and it is not in this subtree, so
               nothing inside the loop can break it. */
            if ((pre[PRE_CAR_FLAGS_1 + slot] & 0x0F) == 0x09)
                pre[PRE_CAR_FLAGS_1 + slot] ^= 0x01;
            int path = object_path(pre, slot);
            paths[path]++;
            c.A = (uint8_t)xs(); c.X = slot; c.Y = (uint8_t)xs();
            c.N = xs() & 1; c.V = xs() & 1; c.Z = xs() & 1; c.C = xs() & 1;
            c.D = 0;
            static uint8_t preCopy[65536];
            memcpy(preCopy, pre, sizeof preCopy);
            subFail += diff_run("draw_track_object", pre, c, draw_track_object,
                                draw_track_object__t6502, liveMask, t, &printed);
            if (path == OBJ_DRAWN && object_block_ran(preCopy, (const uint8_t*)mem, slot))
                blockRan++;
        }
        fail += subFail;
        if (paths[OBJ_EMPTY] == 0 || paths[OBJ_OFFSCREEN] == 0 || paths[OBJ_DRAWN] == 0) {
            printf("[VACUOUS] draw_track_object: one of the three paths was never taken "
                   "(%d empty, %d offscreen, %d drawn)\n",
                   paths[OBJ_EMPTY], paths[OBJ_OFFSCREEN], paths[OBJ_DRAWN]);
            fail++;
        }
        if (blockRan != paths[OBJ_DRAWN]) {
            printf("[BROKEN] draw_track_object: %d of %d drawn cases left the plotter's "
                   "argument block holding something other than what the pre-state says it "
                   "should — the twin and the oracle agree but both are wrong, or a callee "
                   "writes plot_row/plot_column/plot_shape after all\n",
                   paths[OBJ_DRAWN] - blockRan, paths[OBJ_DRAWN]);
            fail++;
        }
        printf("%-32s %7d cases, %d mismatch (must be 0)  live=AXY+flags  "
               "(%d empty / %d offscreen / %d drawn, %d block-checked)\n",
               "draw_track_object", object, subFail,
               paths[OBJ_EMPTY], paths[OBJ_OFFSCREEN], paths[OBJ_DRAWN], blockRan);
    }

    if (want("fill_dash_edge_columns")) {
        int subFail = 0, ran = 0;
        for (t = 0; t < edges; t++) {
            Cpu6502 c = zero_cpu();
            fill_random(pre);
            plant_plotter_chains(pre);
            plant_body_driver_smc(pre);
            /* ⭐⭐ STEERED, AND THIS ONE IS WORTH READING.  Each column's walk runs from the
               scan line it is handed DOWN to dash_block_starts[column], and Y wraps: with a
               uniform byte there the start offset is above the first line 83% of the time, the
               walk goes all the way round 256, and it therefore covers the SAME SET of scan
               lines whatever line it started from — one write per line, each to its own
               address, so a WRONG START LINE produces byte-identical mem[].  A one-line
               sabotage of the second pass' start survived 60 cases and needed 480 to die.
               The real table is what fixes it, not more cases: dash_block_starts holds
               offsets into an $80-byte block and the data always ends at offset $4F
               (symbols.csv), so two thirds of the cases get a start in 0..$4F and the walk
               stops where it does in a real frame.  The rest stay uniform, which is what
               keeps the wrap path covered. */
            if (xs() % 3)
                for (int col = 0x03; col <= 0x22; col++)
                    pre[0x3900 + col] = (uint8_t)(xs() % 0x50);
            c.A = (uint8_t)xs(); c.X = (uint8_t)xs(); c.Y = (uint8_t)xs();
            c.N = xs() & 1; c.V = xs() & 1; c.Z = xs() & 1; c.C = xs() & 1;
            c.D = 0;
            subFail += diff_run("fill_dash_edge_columns", pre, c, fill_dash_edge_columns,
                                fill_dash_edge_columns__t6502, liveMask, t, &printed);
            if (edge_columns_ran((const uint8_t*)mem)) ran++;
        }
        fail += subFail;
        /* ⚠ THE CASE COUNT IS A COMPROMISE IN BOTH DIRECTIONS.  Downward: each case walks up
           to 256 source bytes per column, for seventeen columns, twice over, through
           surface_colour_at.  Upward: this routine's output is SELF-HEALING.  Each of the
           eight iterations of a run writes one byte per scan line into the SAME boundary
           table, so only the last write to a line survives — and as soon as any later
           iteration's walk wraps past a line an earlier iteration got wrong, the two models
           reconverge.  The one-line start-of-run sabotage therefore shows up in ~3% of cases
           even with the table steered, which is what 600 is sized for. */
        if (ran != edges) {
            printf("[VACUOUS] fill_dash_edge_columns: %d of %d cases did not run both "
                   "passes to completion\n", edges - ran, edges);
            fail++;
        }
        printf("%-32s %7d cases, %d mismatch (must be 0)  live=AXY+flags  "
               "(%d/%d ran both passes)\n",
               "fill_dash_edge_columns", edges, subFail, ran, edges);
    }

    unsetenv("REVS_SMC_CONTINUE");
    return fail;
}

int main(int argc, char** argv)
{
    if (argc > 1) { g_filter = &argv[1]; g_nfilter = argc - 1; }

    platform_test_init_headless();
    (void)set_ignore; (void)platform_test_tick_clock; (void)platform_test_clock_addr;

    int fail = 0;

    /* --- fixtures go here --- */
    (void)test_contract;   /* the generic leaf fixture; twin #1 needs a steered one */
    fail += test_irq1v_band_schedule();
    fail += test_view_paint_lines();
    fail += test_view_producers();
    fail += test_body_drivers();

    fail += check_coverage();
    fail += report_unvalidated_natives();

    if (g_nregistered == 0 && VALIDATE_NAMES[0] == 0) {
        printf("no twins registered yet — harness builds and runs clean.\n"
               "  (This is the scaffold state, not a pass: there is nothing to compare.)\n");
        return 0;
    }

    printf("%s\n", fail ? "FAIL" : "PASS");
    return fail ? 1 : 0;
}
