/* Native-twin validation harness.
 *
 * For each function listed in transpile.py's VALIDATE_FUNCS, two versions exist:
 *   <name>()         — the native reimplementation        (src/gen/revs_native.c)
 *   <name>__t6502()  — the faithful 6502 transliteration  (src/gen/revs_gen.c)
 *
 * This harness runs both on the SAME randomised pre-state and diffs the full machine
 * state (all 64 KB of mem[] plus the CPU registers/flags).
 *
 * Build:  make validate            Run one:  make validate FN=<substring>
 *
 * ============================================================================
 * ⭐ WHY THIS FILE LOOKS OVER-ENGINEERED FOR ZERO TWINS
 * ============================================================================
 * The nastiest bug class on the Atari port was **passes `make validate` green, breaks
 * at runtime**, and it bit three separate times.  The postmortem's §3.1 conclusion was
 * to make each failure mode STRUCTURALLY IMPOSSIBLE from twin #1 rather than patching
 * the harness after each one.  So, before the first twin exists:
 *
 *  1. FIXTURE-OR-FAIL.  A function registered in VALIDATE_FUNCS but with no fixture
 *     here used to print PASS having run ZERO comparisons — a vacuous green.  The
 *     transpiler now emits every validated name into src/gen/revs_validate_list.h, and
 *     main() FAILS if any listed name has no registered fixture.  See check_coverage().
 *
 *  2. NO "INCIDENTAL" REGISTER BUCKET.  The old harness reported exit-register diffs as
 *     "incidental" and moved on — but a twin's exit register consumed by a transpiled
 *     caller is a real contract, and one such diff (an exit A=0) shipped a live bug.
 *     Here every fixture must DECLARE which registers are live on exit
 *     (LIVE_NONE / LIVE_A / …).  Anything declared live is a hard failure; anything not
 *     declared is asserted DEAD, which forces the author to have checked the call sites.
 *
 *  3. ENDIANNESS CANNOT HIDE.  mem[] is little-endian (6502).  The Amiga 68000 is
 *     big-endian and this host is little-endian, so aliasing mem[] as uint16_t* / uint32_t*
 *     reads correct here and byte-swapped on the target — green host run, garbage on the
 *     Amiga.  Two countermeasures: `make endian-lint` greps for such aliases, and
 *     ENDIAN_NOTE below records the rule at the point of temptation.  A twin that needs
 *     16/32-bit values lifts them into locals and touches mem[] byte-wise.
 *
 *  4. RANDOMISED INPUTS INCLUDING GATING BYTES.  Fixtures randomise the WHOLE 64 KB by
 *     default (fill_random), not a hand-authored subset, so no branch stays untested
 *     because its gating byte happened to be zero in every case.
 * ============================================================================
 *
 * Deterministic: fixed-seed xorshift PRNG (no wall-clock / rand()), so a green run is
 * reproducible and a regression is bisectable.
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "../src/cpu/cpu.h"

/* Generated by tools/transpile.py: VALIDATE_NAMES[] — every name in VALIDATE_FUNCS.
   Absent until the first `make gen`, so tolerate that while scaffolding. */
#if defined(__has_include)
#  if __has_include("../src/gen/revs_validate_list.h")
#    include "../src/gen/revs_validate_list.h"
#    define HAVE_VALIDATE_LIST 1
#  endif
#endif
#ifndef HAVE_VALIDATE_LIST
static const char* const VALIDATE_NAMES[] = { 0 };
#endif

/* ENDIAN_NOTE: never alias mem[] as uint16_t* / uint32_t* for a general value.  The one
   safe case is a uniform-byte broadcast store (all lanes equal => endianness-neutral),
   and even then the address must be even and the region ISR-untouched.
   See docs/m68k-optimisation.md. */

static uint32_t rng = 0x9D6F1234u;
static uint32_t xs(void) { uint32_t x = rng; x ^= x << 13; x ^= x >> 17; x ^= x << 5; return rng = x; }

/* ---------------------------------------------------------------- test filter */
static char** g_filter  = 0;
static int    g_nfilter = 0;
static int want(const char* name) {
    if (g_nfilter == 0) return 1;
    for (int i = 0; i < g_nfilter; i++)
        if (strstr(name, g_filter[i])) return 1;
    return 0;
}

/* ------------------------------------------------- fixture coverage registry */
enum { MAX_FIXTURES = 256 };
static const char* g_registered[MAX_FIXTURES];
static int         g_nregistered = 0;
static void register_fixture(const char* name) {
    if (g_nregistered < MAX_FIXTURES) g_registered[g_nregistered++] = name;
}
static int is_registered(const char* name) {
    for (int i = 0; i < g_nregistered; i++)
        if (strcmp(g_registered[i], name) == 0) return 1;
    return 0;
}
/* FIXTURE-OR-FAIL: every validated function must have a fixture.  A missing one is a
   HARD FAILURE, not a warning — that is the whole point (see the header, §1). */
static int check_coverage(void) {
    int missing = 0;
    for (int i = 0; VALIDATE_NAMES[i]; i++) {
        if (!is_registered(VALIDATE_NAMES[i])) {
            printf("[NO FIXTURE] %s is in VALIDATE_FUNCS but has no test here — "
                   "a PASS for it would be vacuous (0 comparisons run)\n",
                   VALIDATE_NAMES[i]);
            missing++;
        }
    }
    return missing;
}

/* ------------------------------------------------- live-exit-register contract */
enum {
    LIVE_NONE = 0,
    LIVE_A = 1 << 0, LIVE_X = 1 << 1, LIVE_Y = 1 << 2, LIVE_S = 1 << 3,
    LIVE_FLAGS = 1 << 4          /* N/V/Z/C */
};

/* Per-test contract mask: addresses excluded from the mem[] diff.  Use ONLY for cells
   PROVEN dead after the function returns (no reader before the next write).  Scoped —
   set before a test, clear after — so it never relaxes another function's contract. */
static const uint16_t* g_ignore   = 0;
static int             g_ignore_n = 0;
static void set_ignore(const uint16_t* addrs, int n) { g_ignore = addrs; g_ignore_n = n; }

void platform_test_init_headless(void);
void platform_test_tick_clock(int on);
void platform_test_clock_addr(uint16_t a);

static void fill_random(uint8_t* buf) {
    uint32_t* w = (uint32_t*)buf;
    for (int i = 0; i < 65536 / 4; i++) w[i] = xs();
}

static Cpu6502 zero_cpu(void) {
    Cpu6502 c; memset(&c, 0, sizeof c); c.S = 0xFF; return c;
}

/* Run native vs __t6502 on the SAME pre-state; diff full mem[] + the declared-live
   registers, and assert the undeclared ones really are dead.
   Returns the number of failing cases. */
static int diff_run(const char* name, const uint8_t* pre, Cpu6502 pre_cpu,
                    void (*native)(void), void (*t6502)(void), unsigned liveMask,
                    int t, int* printed)
{
    static uint8_t ref_mem[65536];

    memcpy((void*)mem, pre, 65536); cpu = pre_cpu;
    t6502();
    memcpy(ref_mem, (void*)mem, sizeof ref_mem);
    Cpu6502 ref_cpu = cpu;

    memcpy((void*)mem, pre, 65536); cpu = pre_cpu;
    native();

    for (int i = 0; i < g_ignore_n; i++) ref_mem[g_ignore[i]] = mem[g_ignore[i]];

    int failed = 0;
    if (memcmp((const void*)mem, ref_mem, 65536) != 0) {
        failed = 1;
        for (int i = 0; i < 65536 && *printed < 12; i++)
            if (mem[i] != ref_mem[i]) {
                printf("[MEM DIFF] %s case %d  $%04X  ref=$%02X native=$%02X\n",
                       name, t, i, ref_mem[i], mem[i]);
                (*printed)++;
            }
    }

    /* Declared-live registers are part of the contract — a diff is a failure. */
#define CHECK_REG(bit, field, label)                                              \
    if ((liveMask & (bit)) && cpu.field != ref_cpu.field) {                       \
        failed = 1;                                                              \
        if (*printed < 12) {                                                     \
            printf("[REG DIFF] %s case %d  %s  ref=$%02X native=$%02X (declared live)\n", \
                   name, t, label, ref_cpu.field, cpu.field); (*printed)++;      \
        }                                                                        \
    }
    CHECK_REG(LIVE_A, A, "A")
    CHECK_REG(LIVE_X, X, "X")
    CHECK_REG(LIVE_Y, Y, "Y")
    CHECK_REG(LIVE_S, S, "S")
#undef CHECK_REG
    if ((liveMask & LIVE_FLAGS) &&
        (cpu.N != ref_cpu.N || cpu.V != ref_cpu.V || cpu.Z != ref_cpu.Z || cpu.C != ref_cpu.C)) {
        failed = 1;
        if (*printed < 12) {
            printf("[REG DIFF] %s case %d  flags NVZC ref=%d%d%d%d native=%d%d%d%d (declared live)\n",
                   name, t, ref_cpu.N, ref_cpu.V, ref_cpu.Z, ref_cpu.C,
                   cpu.N, cpu.V, cpu.Z, cpu.C);
            (*printed)++;
        }
    }
    return failed;
}

/* Generic fixture: randomised whole-mem[] contract test with an explicit live-exit-
   register declaration.  Fits any leaf observed purely through mem[] plus the registers
   it declares.  Anything more specific (a restricted input domain, a stack-aware leaf)
   gets its own test_<name>() — but it still calls diff_run and still declares liveMask. */
static int test_contract(const char* name, void (*native)(void), void (*t6502)(void),
                         unsigned liveMask, int cases)
{
    register_fixture(name);
    if (!want(name)) return 0;
    static uint8_t pre[65536];
    int fail = 0, printed = 0;
    for (int t = 0; t < cases; t++) {
        fill_random(pre);
        fail += diff_run(name, pre, zero_cpu(), native, t6502, liveMask, t, &printed);
    }
    printf("%-32s %7d cases, %d mismatch (must be 0)  live=%s%s%s%s%s\n",
           name, cases, fail,
           (liveMask & LIVE_A) ? "A" : "", (liveMask & LIVE_X) ? "X" : "",
           (liveMask & LIVE_Y) ? "Y" : "", (liveMask & LIVE_S) ? "S" : "",
           (liveMask == LIVE_NONE) ? "none" : ((liveMask & LIVE_FLAGS) ? "+flags" : ""));
    return fail;
}

/* ==========================================================================
   FIXTURES
   ==========================================================================
   None yet — no twin exists.  Add one per twin, e.g.

       fail += test_contract("divide_16x16", divide_16x16, divide_16x16__t6502,
                             LIVE_NONE, 200000);

   ⚠ Registering the function in transpile.py's VALIDATE_FUNCS is only HALF the job:
   without a fixture here, check_coverage() now fails the run rather than letting a
   vacuous PASS through.  That is deliberate.
   ========================================================================== */

int main(int argc, char** argv)
{
    if (argc > 1) { g_filter = &argv[1]; g_nfilter = argc - 1; }

    platform_test_init_headless();
    (void)set_ignore; (void)platform_test_tick_clock; (void)platform_test_clock_addr;

    int fail = 0;

    /* --- fixtures go here --- */
    (void)test_contract;   /* remove once the first fixture is registered */

    fail += check_coverage();

    if (g_nregistered == 0 && VALIDATE_NAMES[0] == 0) {
        printf("no twins registered yet — harness builds and runs clean.\n"
               "  (This is the scaffold state, not a pass: there is nothing to compare.)\n");
        return 0;
    }

    printf("%s\n", fail ? "FAIL" : "PASS");
    return fail ? 1 : 0;
}
