/* mos.cpp — the MOS (Acorn OS) call layer.
 *
 * ⭐ THE STRUCTURAL DIFFERENCE FROM THE ATARI PORT.  Rescue on Fractalus! simply *replaced*
 * the Atari OS; Revs genuinely runs under the BBC MOS and reaches the keyboard, the
 * analogue steering and the sound scheduler through OS entry points.  Those are `JSR`
 * targets into ROM, not bus addresses, so `bus.h` never sees them — the transpiler emits
 * `platform_mos_call(entry)` and this file is what services it.
 *
 * ⭐ THE SURFACE IS CLOSED, NOT OPEN-ENDED.  Phase 2 enumerated it from the disassembly
 * before a line of this was written (`docs/static-map.md` §MOS calls / `docs/bbc-hardware.md`):
 * **four entries, 17 call sites, 8 distinct OSBYTE reason codes**.  Every one of them is
 * handled below and tagged with its site address.  A call that reaches the `default:` arm
 * is therefore a *discovery*, not a gap to shrug at — it is counted in g_mosUnknown* so a
 * headless run reports it instead of silently returning a plausible zero.  (Same discipline
 * as Platform::smcUnhandled: the failure mode this project keeps paying for is a stub that
 * returns something reasonable and reads exactly like working code.)
 *
 * WHY THIS IS SHARED, NOT PER-BACKEND.  OSBYTE 129's contract (X=Y=$FF when the key is
 * held) is the 6502's ABI, identical on both backends; only *where the input comes from*
 * differs.  So the dispatch lives here once and the four genuinely platform-specific
 * answers are virtual hooks — keyDown / adcAxis / adcButtons / rdch / wrch.  Duplicating
 * the dispatch per backend would let the host and the target disagree about the OS itself,
 * which is the one thing that must not vary between them.
 */
#include "platform.h"
#include "teletext.h"
#include "sound.h"
#include "mos_font.h"
#include "../cpu/cpu.h"

enum { MOSLOG_MAX = 4096 };   /* ⚠ duplicated in tools/validate_native.c */

/* ⚠ Counters, not silence.  Listed in amiga/Makefile PROBE_SYMS so --gc-sections cannot
   drop them and leave gdb printing instruction bytes as a value (docs/method-lessons.md). */
extern "C" {
volatile unsigned long g_mosUnknownCount = 0;   /* MOS calls that hit no handler */
volatile uint16_t      g_mosUnknownEntry = 0;   /* ...the last such entry ($FFF4/$FFF1/...) */
volatile uint16_t      g_mosUnknownA     = 0;   /* ...and its reason code (A) */
/* OSWORD 10 reads a character definition — the race view's bitmap text (lap times and the
   like).  We have no MOS ROM and will not lift Acorn's font, so the 96 printable glyphs are
   DRAWN: src/platform/mos_font.h, generated by tools/gen_mos_font.py.
   ⚠ The measured code set is a FLOOR, not a closed surface: one practice race asks for 15
   codes, and competition mode adds driver names and digits.  So a request outside the drawn
   range is COUNTED rather than quietly blanked — same discipline as g_mosUnknownCount. */
volatile unsigned long g_mosCharDefCount = 0;   /* OSWORD 10 calls served */
volatile unsigned long g_mosCharDefOutOfRange = 0; /* ...of those, codes with no drawn glyph */
volatile uint16_t      g_mosCharDefLastBad = 0;    /* ...the last such code */

/* ⭐ THE MOS-CALL TRACE's storage — see Platform::mosCall for why it exists.
   ⚠ REVS_HW_TRACE-ONLY, and deliberately: at MOSLOG_MAX = 4096 these four arrays are 16 KB
   of BSS, which is real memory on a 512 KB A500 for something only the host differential
   ever reads.
   ⚠ MOSLOG_MAX is duplicated in tools/validate_native.c, the same arrangement HWLOG_MAX
   already has; the consumer clamps to its own copy rather than trusting them to match. */
#ifdef REVS_HW_TRACE
uint16_t g_mosLogEntry[MOSLOG_MAX];
uint8_t  g_mosLogA[MOSLOG_MAX], g_mosLogX[MOSLOG_MAX], g_mosLogY[MOSLOG_MAX];
unsigned g_mosLogN = 0;
unsigned g_mosLogOverflow = 0;
#endif
}

/* --------------------------------------------------------------------------
   OSBYTE ($FFF4) — A = reason code, X/Y = parameters, X/Y = results.
   -------------------------------------------------------------------------- */
static MosRegs osbyte(MosRegs r)
{
    switch (r.a) {

    /* 0 — read the OS version.  ⭐ NOT IN THE PHASE 2 INVENTORY, and finding it is the
       point of the unknown-call counter: the inventory's reason codes were recovered by a
       nearest-preceding-`LDA #imm` heuristic and marked [DERIVED, heuristic] for exactly
       this reason (docs/bbc-hardware.md).  A site whose A is computed rather than
       immediate is invisible to that scan, and this is one.
       Contract: X=0 asks the MOS to generate an error; X<>0 returns the version in X.
       Revs cannot want the error path from a running engine, so answer as MOS 1.20 — the
       ROM the reference loop boots (docs/bbc-reference-loop.md). */
    case 0x00:
        r.x = 0x01;          /* OS 1.20 */
        break;

    /* 2 — select input stream.  Site $630A (X=0, keyboard).  Returns X = previous
       setting.  Nothing in Revs reads it back; keep the register write faithful anyway. */
    case 0x02:
        r.x = 0x00;
        break;

    /* 4 — cursor/copy key behaviour.  Site $3856 (X=1: cursor keys act as normal keys,
       which is exactly why the game can INKEY them).  Returns X = previous. */
    case 0x04:
        r.x = 0x00;
        break;

    /* 21 — flush buffer X.  Sites $0E6B (sound channel buffers 4-7) and $6311 (keyboard
       buffer 0).  The keyboard is polled, not buffered, so that one is a genuine no-op.
       ⭐ THE SOUND BUFFERS ARE NOT.  Flushing buffer 4+channel SILENCES the channel on a real
       BBC (measured: attenuation 15, and the divider resets), and `sound_stop_channel` ($0E5A)
       is the ONLY way Revs ever stops a sound — every one of them has duration 255 = play
       forever.  Treat this as a no-op and the engine noise never goes quiet. */
    case 0x15:
        if ((r.x & 0xFC) == 0x04) snd_flush_channel((uint8_t)(r.x & 3));
        break;

    /* 126 — acknowledge ESCAPE.  Site $6349, inside console_io's line editor.  Returns
       X = $FF if an ESCAPE condition was cleared, 0 if there was none.  The port never
       raises ESCAPE, so: none. */
    case 0x7E:
        r.x = 0x00;
        break;

    /* 128 (ADVAL) — ⭐ THE STEERING INPUT.  Sites $168E (X=0) and $5041 (X=channel).
         X=0  → X,Y = the "last conversion / fire buttons" word.  $168E does TXA:AND #$01,
                so only fire button 1 is ever looked at.
         X=1..4 → X,Y = the 16-bit conversion for that channel.  $503F does TYA:ADC #$80,
                i.e. it uses ONLY the high byte, biased so $80 is centre. */
    case 0x80: {
        if (r.x == 0x00) {
            r.x = platform ? platform->adcButtons() : 0x00;
            r.y = 0x00;
        } else {
            uint16_t v = platform ? platform->adcAxis(r.x) : 0x8000;
            r.x = (uint8_t)(v & 0xFF);
            r.y = (uint8_t)(v >> 8);
        }
        break;
    }

    /* 129 (INKEY) — the input primitive, 17 callers by way of kbd_test_key ($0E50).
         Y=$FF → NEGATIVE INKEY: is the key with internal number -(256-X) held?
                 Returns X=Y=$FF when held, X=Y=$00 when not.  kbd_test_key's caller
                 tests it with CPX #$FF, so Z set means "held".
         Y=$7F → machine-type check.  Revs never issues it; answer as a BBC B (0) rather
                 than fall through to the unknown-call counter if it ever appears. */
    case 0x81:
        if (r.y == 0xFF) {
            bool held = platform ? platform->keyDown(r.x) : false;
            r.x = held ? 0xFF : 0x00;
            r.y = held ? 0xFF : 0x00;
        } else if (r.y == 0x7F) {
            r.x = 0x00;              /* BBC B */
            r.y = 0x00;
        } else {
            /* Timed read of a character.  Not a site Revs has; report rather than guess. */
            g_mosUnknownEntry = 0xFFF4; g_mosUnknownA = 0x81; g_mosUnknownCount++;
            r.x = 0x00; r.y = 0xFF;   /* "timed out, no character" */
        }
        break;

    /* 154 — write the Video ULA control register ($FE20) through its OS copy at $0248.
       Site $4DF5 with X=$C4.  Keep BOTH effects: the shadow byte the MOS maintains AND
       the hardware write, because the port's own display code reads the seam at $FE20.
       (bus_write routes $FE20 to Platform::hwWrite, which is where the copper list will
       eventually pick the mode/palette up — Phase 5.) */
    case 0x9A:
        mem[0x0248] = r.x;
        if (platform) platform->hwWrite(0xFE20, r.x);
        break;

    /* 190 — read/write the uPD7002 conversion type (resolution).  Site $3879 with X=$20.
       Returns X = previous value.  Purely a property of the ADC we are substituting a
       mouse for, so there is nothing behind it to change. */
    case 0xBE:
        r.x = 0x00;
        break;

    default:
        /* ⚠ Not in the Phase 2 inventory.  Either the inventory is incomplete or a
           self-modified site produced a new reason code — both are findings. */
        g_mosUnknownEntry = 0xFFF4;
        g_mosUnknownA     = r.a;
        g_mosUnknownCount++;
        break;
    }
    return r;
}

/* --------------------------------------------------------------------------
   OSWORD ($FFF1) — A = reason code, (X,Y) = a control block in mem[].
   -------------------------------------------------------------------------- */
static MosRegs osword(MosRegs r)
{
    uint16_t blk = (uint16_t)r.x | ((uint16_t)r.y << 8);

    switch (r.a) {

    /* ⭐ 7 — SOUND, and 8 — define an ENVELOPE.  Sites $0B70 (both: `sound_queue` $0B4A reaches
       it with A=7, `sound_envelope` $0B65 with A=8) — one JSR, two reason codes, which is exactly
       why the Phase 2 nearest-`LDA #imm` scan never attributed reason 7 to it.
       Revs drives the SN76489 ONLY through here, so what is behind these two arms is the OS's
       whole sound scheduler: src/platform/sound.c, validated tick-for-tick against a real BBC by
       `make sound`.  The blocks are copied out of mem[] a byte at a time — never aliased as
       words, because mem[] is little-endian and the Amiga is not (make endian-lint).
       ⚠ Accepting a command is not the same as playing it: something has to call `snd_tick()` at
       100 Hz.  The Amiga backend does (RevsAudio.h); the HOST DELIBERATELY DOES NOT, because it
       has no audio hardware and no renderer by design — the model's test is `make sound`, not a
       host that half-plays it. */
    case 0x07: {
        uint8_t b[8];
        for (int i = 0; i < 8; i++) b[i] = mem[(uint16_t)(blk + i)];
        snd_sound(b);
        break;
    }

    case 0x08: {
        uint8_t b[14];
        for (int i = 0; i < 14; i++) b[i] = mem[(uint16_t)(blk + i)];
        snd_envelope(b);
        break;
    }

    /* ⭐ 10 — read a character definition.  THE RACE VIEW'S TEXT PATH, and the other half of
       vdu_char_def ($5092) from MODE 7's: $5096 stores the code here, calls this, and plots the
       eight returned bytes straight into the frame buffer at $50D1 (`STA ($70),Y`, walking
       upward a character row at a time).  Site $50A7 with X=$C3, Y=$62 — the block is at
       $62C3, NOT $00C3: X and Y are the low and high bytes of the address.
       Block: byte 0 = character code (in), bytes 1..8 = the 8x8 bitmap (out), row 0 first,
       bit 7 = leftmost pixel.  That is exactly g_mosFont's layout, so this is a copy.
       ⚠ The bytes are copied ONE AT A TIME into mem[] — never memcpy'd through a wide type —
       because mem[] is little-endian and the Amiga is not (make endian-lint).
       ⚠ Glyphs DRAWN, not extracted; see mos_font.h. */
    case 0x0A: {
        uint8_t code = mem[blk];
        g_mosCharDefCount++;
        if (code >= MOS_FONT_FIRST && code <= MOS_FONT_LAST) {
            const uint8_t *glyph = g_mosFont[code - MOS_FONT_FIRST];
            for (int i = 0; i < 8; i++) mem[(uint16_t)(blk + 1 + i)] = glyph[i];
        } else {
            /* A control code or a user-defined character.  The MOS would return the RAM
               definition at $0C00+; Revs has never asked for one, so report it instead of
               inventing a shape — a blank glyph reads exactly like a working renderer. */
            for (int i = 1; i <= 8; i++) mem[(uint16_t)(blk + i)] = 0x00;
            g_mosCharDefOutOfRange++;
            g_mosCharDefLastBad = code;
        }
        break;
    }

    default:
        g_mosUnknownEntry = 0xFFF1;
        g_mosUnknownA     = r.a;
        g_mosUnknownCount++;
        break;
    }
    return r;
}

/* --------------------------------------------------------------------------
   The dispatcher.
   -------------------------------------------------------------------------- */
MosRegs Platform::mosCall(uint16_t entry, MosRegs in)
{
#ifdef REVS_HW_TRACE
    /* ⭐⭐ THE MOS-CALL TRACE, and it exists for the same reason bbc_hw's write trace does:
       a routine whose whole output is an OS CALL is invisible to a mem[] diff.
       Found by sabotage, 2026-08-18, on twin #77 sound_stop_channel — delete its already-idle
       guard and it issues an OSBYTE 21 on EVERY call instead of only when the channel is
       playing, silencing a channel the game meant to leave alone.  mem[] is byte-identical
       (the guarded store writes 0 over 0), the registers are identical (PLA restores A and
       OSBYTE 21 preserves X), and 1000 cases PASSED.
       ⚠ What is logged is the ENTRY and A/X/Y AS HANDED OVER, because that is the whole of
       what the 6502 gives the OS; whether the MOS then does the right thing with them is
       `make sound` / `make mode7`'s question, not this trace's. */
    if (g_mosLogN < MOSLOG_MAX) {
        g_mosLogEntry[g_mosLogN] = entry;
        g_mosLogA[g_mosLogN] = in.a;
        g_mosLogX[g_mosLogN] = in.x;
        g_mosLogY[g_mosLogN] = in.y;
        g_mosLogN++;
    } else g_mosLogOverflow++;
#endif

    switch (entry) {

    case 0xFFF4:   /* OSBYTE */
        return osbyte(in);

    case 0xFFF1:   /* OSWORD */
        return osword(in);

    /* OSWRCH — VDU output.  Four sites: VDU 127 (delete, $3EF3), VDU 7 (bell, $633F),
       VDU 156 ($6651) and one from a variable ($50F6).  All of them belong to the MODE 7
       front end / line editor.
       ⭐ THE VDU DRIVER IS SHARED, NOT PER-BACKEND.  It maintains the teletext page in mem[]
       exactly where the MOS would, which is the majority of the front end's screen writes
       (measured: 29878 MOS writes vs 1105 from the game) and is faithful BBC behaviour rather
       than an Amiga decision — so it belongs here, on the same side of the seam as bbc_hw.cpp
       (docs/faithfulness-seam.md).  `make mode7` validates it byte-for-byte against a real
       BBC.  The backend still gets the byte, for anything display-side it wants to notice. */
    case 0xFFEE:
        tt_vdu(in.a);
        if (platform) platform->wrch(in.a);
        return in;

    /* OSRDCH — read a character, blocking.  One site: $6316, console_io's line editor
       (entering a driver name).  Returns A = the character, C = 0; C = 1 signals an
       ESCAPE condition.
       ⚠ Returning C=1 here is a HANG: $6319 branches to $6345, which acknowledges the
       ESCAPE and jumps straight back to the read.  The backend's rdch() therefore must
       always return a real character; the default (CR) ends the line immediately. */
    case 0xFFE0:
        in.a = platform ? platform->rdch() : 0x0D;
        in.c = 0;
        return in;

    default:
        g_mosUnknownEntry = entry;
        g_mosUnknownA     = in.a;
        g_mosUnknownCount++;
        return in;
    }
}

/* --------------------------------------------------------------------------
   Default input answers.  A backend overrides the ones it can really answer.
   -------------------------------------------------------------------------- */
bool    Platform::keyDown(uint8_t /*negInkeyX*/) { return false; }
uint8_t Platform::adcButtons()                   { return 0x00; }
/* $8000 is centre: adc_read ($503F) takes the HIGH byte and adds $80, so $80 → 0 offset. */
uint16_t Platform::adcAxis(uint8_t /*channel*/)  { return 0x8000; }
uint8_t Platform::rdch()                         { return 0x0D; }   /* CR: end of line */
void    Platform::wrch(uint8_t /*c*/)            {}
