#ifndef REVS_TRACKMENU_H
#define REVS_TRACKMENU_H
/* trackmenu.h — THE CIRCUIT MENU.
 *
 * ⚠ The MODEL is shared and validated; only the Amiga DRIVES it.  Everything here is pure — it
 * paints into mem[] and is advanced by a key mask and a field count — so the differential
 * (tools/validate_trackmenu.c) runs it on the host with no display at all.  What the Amiga adds is
 * the keyboard and the frame pump (PlatformAmiga::runTrackMenu), and the host build deliberately
 * has neither: it has no renderer by design (src/platform/host/PlatformHost.h), so it keeps
 * selecting a circuit the way it always has, from the build.
 *
 * ═══════════════════════════════════════════════════════════════════════════════════════════
 * WHY THIS FILE IS PORT-AUTHORED, AND WHY IT IS STILL VALIDATED
 * ═══════════════════════════════════════════════════════════════════════════════════════════
 * The circuit menu on the disc is `REVSMEN`, and it is BASIC — 43 lines that show the 5TRSCRN
 * title page, draw a menu, read a digit and then `*LO.<TRACK>` / run the engine.  This port does
 * not run BASIC, so unlike every other screen in the game this one has to be WRITTEN rather than
 * transliterated (docs/phases.md §5d).
 *
 * ⭐ That is exactly why it has a fixture.  Port-authored is not a licence to eyeball it: the real
 * page was recorded off a real BBC (`tools/bbc_probe_trackmenu.mjs`) and `make trackmenu` diffs
 * what this file paints against it, byte for byte, for the base page and for all five selections.
 * The whole page — every attribute code, every column — is therefore MEASURED, not designed.
 *
 * Everything is painted through `tt_vdu()`, the same validated MOS VDU driver the engine's own
 * front end goes through (`teletext.h`), so screen RAM stays the single source of truth and the
 * SAA5050 decode is shared with everything else on screen.
 *
 * ── WHAT THE REAL PAGE IS ─────────────────────────────────────────────────────────────────
 *
 *     row  2   VDU 151 then 39x VDU 185         a graphics-white mosaic rule
 *     rows 3,4 VDU 141, 133, "R", 131, "E", …   "REVS REVS REVS", double height, twice
 *     row  5   the rule again
 *     row 10   VDU 134, 136, "    PRESS"        cyan, FLASHING (so it needs tt_tick_flash())
 *     rows 12,14,16,18,20                       the circuits: digit cyan-on-blue, name yellow
 *     row 23   "     PRESS SPACE BAR TO CONTINUE"   — printed only AFTER a digit is accepted
 *
 * and selecting option N recolours that row's digit field from blue to RED.  ⚠ MEASURED: that is
 * TWO changed bytes, not the three `VDU 129,157,131` would suggest — column 6 already holds $9D,
 * so the write is idempotent there.  Trusting the BASIC listing over the recorded page would have
 * made a correct implementation look like it had an off-by-one.
 *
 * ── THE ONE DELIBERATE DIVERGENCE ─────────────────────────────────────────────────────────
 * ⭐ A SIXTH OPTION, NURBURGRING (user decision).  The commercial disc has five circuits; this
 * port also carries the Nürburgring block from a hack disc, and until now it was reachable only
 * by rebuilding with `make TRACK=5`.  It is appended as option 6 — same emitter, same row pitch,
 * one row further down — and it is present only when the generated table actually has it
 * (`REVS_TRACK_COUNT`, which is 5 on a checkout without that disc).
 *
 * ⚠ So the shipped page is NOT the real page, and the differential is honest about it: `make
 * trackmenu` paints with `TM_OPTIONS_FAITHFUL` (5) and diffs that, which proves every row,
 * attribute and column the two configurations share.  The sixth row is the only thing the
 * fixture does not cover, and it is generated by the same loop as the other five.
 *
 * ── THE OPTION ORDER IS NOT THE TABLE ORDER ───────────────────────────────────────────────
 * ⚠⚠ REVSMEN lists BRANDS, DONINGTON, OULTON, SNETTERTON, SILVERSTONE; `revs_tracks[]` is
 * Silverstone-first (it is the engine's own default).  So option 5 is track 0, and an
 * option→index table is unavoidable.  A wrong entry there would install a circuit that works
 * perfectly and is not the one the player chose — the plausible-looking wrong game this project
 * keeps paying for — so `tm_begin()` CROSS-CHECKS every entry against `revs_tracks[].name` and
 * counts a mismatch in `g_tmMisrouted`.  Reordering `gen_tracks.py`'s CIRCUITS therefore breaks
 * loudly instead of silently.
 */
#include "teletext.h"

#ifdef __cplusplus
extern "C" {
#endif

/* The five options the real page has.  `make trackmenu` diffs this configuration. */
#define TM_OPTIONS_FAITHFUL  5u
/* The most this page can hold.  ⚠ When the sixth option (Nürburgring) is present the PRESS line
   and the circuits below it are lifted two rows (trackmenu.c s_rowShift; the rules and REVS logo
   stay put) so option 6 lands on row 20 with rows 21-22 blank before the row-23 SPACE prompt — the
   same spacing the faithful five-option page has, which `make trackmenu` records.  The faithful
   page is not lifted. */
#define TM_OPTIONS_MAX       6u

/* ⭐ MEASURED, not chosen: 10900001 cycles at 2 MHz between the title page appearing and the menu
   page being complete on a real BBC (`tools/bbc_probe_trackmenu.mjs` prints it).  That is REVSMEN
   line 50's `FOR X=0 TO 10000:NEXT` plus the disc access, and it is counted here in DISPLAY
   FIELDS because that is what the backend can actually count — 5.45 s x 50 Hz. */
#define TM_TITLE_FIELDS      273u

/* Where the menu is in its two-key sequence.  The real program's shape, kept: a digit selects and
   is final (REVSMEN's REPEAT exits on the first one and never asks again), then SPACE confirms. */
typedef enum {
    TM_TITLE = 0,   /* the 5TRSCRN title page is up, waiting out the dwell */
    TM_SELECT,      /* the menu is up, no option chosen */
    TM_CONFIRM,     /* an option is highlighted, waiting for SPACE */
    TM_FINISHED     /* the choice is made — tm_track() is the answer */
} TmPhase;

/* The keys, as a bitmask, so the backend never has to know a BBC key code.  Bit 0 is SPACE and
   bits 1..6 are the options; `tm_key_codes[]` is the negative-INKEY byte for each bit, which is
   what OSBYTE 129 (and so RevsInput::keyDown) wants. */
#define TM_KEY_SPACE     0x01u
#define TM_KEY_OPTION(n) (1u << (n))          /* n = 1..6 */
extern const unsigned char tm_key_codes[TM_OPTIONS_MAX + 1];

/* ── diagnostics.  ⚠ every one of these is in amiga/Makefile PROBE_SYMS ──────────────────── */
extern volatile unsigned char  g_tmPhase;      /* TmPhase, for a probe */
extern volatile unsigned char  g_tmOption;     /* 1..6 once chosen, else 0 */
extern volatile unsigned char  g_tmTrack;      /* the revs_tracks[] index it maps to */
extern volatile unsigned short g_tmMisrouted;  /* option→index entries the cross-check rejects */
extern volatile unsigned short g_tmRefusals;   /* choices revs_track_install() refused */
extern volatile unsigned long  g_tmFields;     /* fields the menu has been up for */

/* Paint the title page and start the sequence.  `options` is how many circuits to offer, clamped
   to what this build has; pass TM_OPTIONS_FAITHFUL to reproduce the disc's page exactly. */
void tm_begin(unsigned options);

/* Advance by `fields` display fields, with `keys` held (a TM_KEY_* mask).  Repaints only when
   something changes, so it is safe to call every frame. */
void tm_tick(unsigned keys, unsigned fields);

/* Which option installs `track`, or 0 if none does.  ⭐ The inverse of the option table, and the
 * reason it is public: an unattended build has to answer the menu with the circuit `make TRACK=n`
 * asked for, and open-coding that mapping at the call site is how the two copies drift apart. */
unsigned tm_option_for_track(unsigned track);

int      tm_finished(void);
unsigned tm_phase(void);
/* The chosen option (1..6, 0 if none) and the revs_tracks[] index it means. */
unsigned tm_option(void);
unsigned tm_track(void);

/* ⚠ The choice was REFUSED by revs_track_install() — say so on the page and go back to the menu.
 * A silent fall back to Silverstone is the one outcome this must never have: the player would be
 * driving a circuit they did not pick, which is indistinguishable from the port being broken.
 * (No circuit in this build is refused today; `docs/phases.md` §5 has the history of why the
 * mechanism exists anyway.)
 */
void tm_reject(void);

#ifdef __cplusplus
}
#endif

#endif /* REVS_TRACKMENU_H */
